### PR TITLE
Fix issue 15806 ("aspire stop" is not cleaning up application containers)

### LINKED ISSUE #15806: "aspire stop" is not gracefully shutting down the docker containers it starts.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

This is the description I got from Claude Code. I poked around and it seems accurate:

```
  aspire start = LaunchDetachedAsync = launches aspire run as a background child process. Because the CLI launched the AppHost, CliProcessId is always
  set.

  When aspire stop runs, it hits this logic in StopCommand.cs:198-205:

  var cliProcessId = appHostInfo?.CliProcessId;

  if (cliProcessId is int cliPid)        // <-- always true for aspire start
  {
      SendStopSignal(cliPid);             // <-- Process.Kill(entireProcessTree: true)
  }
  else
  {
      // RPC graceful path - never reached
      rpcSucceeded = await connection.StopAppHostAsync(cancellationToken);
  }

  Meanwhile, RunningInstanceManager.StopRunningInstanceAsync (used when aspire start detects a previous instance is already running) does the right
  thing at line 64:

  await backchannel.StopAppHostAsync(cancellationToken);  // graceful!
```

! aspire --version
  ⎿  13.2.0+1b339b0aab41b049e8e0d21ed1a79596cf8b8509

### Expected Behavior

I can run "aspire stop" and my docker containers (the ones not marked as persistent at least) are properly shut down.

### Steps To Reproduce

- "aspire start" a project that runs docker containers (I did this on Windows 11 with Docker for Windows)
- "aspire stop"
- see containers still running.

### Exceptions (if any)

_No response_

### .NET Version info

  ⎿  .NET SDK:
      Version:           10.0.201
      Commit:            4d3023de60
      Workload version:  10.0.200-manifests.121cc9e6
      MSBuild version:   18.3.0-release-26153-122+4d3023de6

     Runtime Environment:
      OS Name:     Windows
      OS Version:  10.0.26200
      OS Platform: Windows
      RID:         win-x64
      Base Path:   C:\Program Files\dotnet\sdk\10.0.201\

     .NET workloads installed:
      [maccatalyst]
        Installation Source: VS 18.4.11620.152
        Manifest Version:    26.2.10217/10.0.100
        Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.maccatalyst\26.2.10217\WorkloadManifest.json
        Install Type:              Msi

      [maui-windows]
        Installation Source: VS 18.4.11620.152
        Manifest Version:    10.0.20/10.0.100
        Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.maui\10.0.20\WorkloadManifest.json
        Install Type:              Msi

      [ios]
        Installation Source: VS 18.4.11620.152
        Manifest Version:    26.2.10217/10.0.100
        Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.ios\26.2.10217\WorkloadManifest.json
        Install Type:              Msi

      [android]
        Installation Source: VS 18.4.11620.152
        Manifest Version:    36.1.30/10.0.100
        Manifest Path:       C:\Program Files\dotnet\sdk-manifests\10.0.100\microsoft.net.sdk.android\36.1.30\WorkloadManifest.json
        Install Type:              Msi

     Configured to use workload sets when installing new manifests.
     No workload sets are installed. Run "dotnet workload restore" to install a workload set.

     Host:
       Version:      10.0.5
       Architecture: x64
       Commit:       a612c2a105

     .NET SDKs installed:
       7.0.410 [C:\Program Files\dotnet\sdk]
       8.0.419 [C:\Program Files\dotnet\sdk]
       10.0.201 [C:\Program Files\dotnet\sdk]

     .NET runtimes installed:
       Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
       Microsoft.AspNetCore.App 8.0.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
       Microsoft.AspNetCore.App 9.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
       Microsoft.AspNetCore.App 10.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
       Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
       Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
       Microsoft.NETCore.App 8.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
       Microsoft.NETCore.App 9.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
       Microsoft.NETCore.App 10.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
       Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
       Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
       Microsoft.WindowsDesktop.App 8.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
       Microsoft.WindowsDesktop.App 9.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
       Microsoft.WindowsDesktop.App 10.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

     Other architectures found:
       x86   [C:\Program Files (x86)\dotnet]
         registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

     Environment variables:
       Not set

     global.json file:
       E:\code\work\github\aspire\global.json

     Learn more:
       https://aka.ms/dotnet/info

     Download .NET:
       https://aka.ms/dotnet/download

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by karolz-ms**
Fixes https://github.com/microsoft/aspire/issues/15806

The main issue was we were that the `stop` command implementation was killing entire detached CLI process tree, including all DCP processes, which prevented DCP from doing proper cleanup. On Unix-like systems we are able to avoid that by detaching ourselves from the application host process tree, but on Windows manipulating the process tree like that is not possible. Fixed by implementing graceful shutdown request (SIGTERM on Unix-like systems, Ctrl+Break console event on Windows) and limiting the process killing to application host and detached CLI only.

While doing this work I also unified some parts of process-related logic between the CLI and "CLI orphan detector", and enhanced the use of process start time to make sure we are not killing processes that happen to reuse CLI process ID.

### CODE REVIEW

File: src/Shared/ProcessSignaler.cs [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+    {
+        var process = TryGetRunningProcess(pid, expectedStartTime, logger);
+        if (process is { })
+        {
+            process.Dispose();
+        }
+
+        if (OperatingSystem.IsWindows())
+        {
+            RequestGracefulShutdownWindows(pid, logger);
```
[the remark this answers is not in the document]
Comment (karolz-ms) [reply src/Shared/ProcessSignaler.cs:25]: That is right-I forgot to push the final version of the code from my local branch.

File: src/Shared/ProcessSignaler.cs [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+    }
+
+    private static bool AreClose(DateTimeOffset? expectedStartTime, DateTime processStartTime, TimeSpan? tolerance = default)
+    {
+        if (expectedStartTime is null)
+        {
+            return true;
+        }
+
+        tolerance ??= TimeSpan.FromMilliseconds(1);
```
[the remark this answers is not in the document]
Comment (karolz-ms) [reply src/Shared/ProcessSignaler.cs]: No that is not the case. We compare times with 1 ms default tolerance mainly to avoid serialization/deserialization rounding errors. If process startup time differs by more than 1 second, we should treat the startup time check as failed.

File: src/Shared/ProcessSignaler.cs [hunk 3]
```diff
@@ -0,0 +1,114 @@
...
+    private const uint CtrlCEvent = 0;
+
+    private static void RequestGracefulShutdownWindows(int pid, ILogger logger)
+    {
+        var success = GenerateConsoleCtrlEvent(CtrlCEvent, (uint)pid);
+        if (!success)
+        {
+            // Best effort.
+            logger.LogWarning("Could not gracefully stop Aspire application host process {Pid}", pid);
+        }
```
[the remark this answers is not in the document]
Comment (karolz-ms) [reply src/Shared/ProcessSignaler.cs]: I pushed outdated code initially, this is fixed.

File: src/Shared/ProcessSignaler.cs [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+        {
+            var process = Process.GetProcessById(pid);
+            if (expectedStartTime is not null && !AreClose(expectedStartTime, process.StartTime))
+            {
+                logger.LogDebug("Process {Pid} start time {ProcessStartTime} does not match expected start time {ExpectedStartTime}", pid, process.StartTime, expectedStartTime);
+                return null; // Do not return processes that do not match the expected start time
+            }
+
+            if (process.HasExited)
+            {
```
[the remark this answers is not in the document]
Comment (karolz-ms) [reply src/Shared/ProcessSignaler.cs:56]: That's fair. Fixed.

File: src/Shared/ProcessSignaler.cs [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+    }
+
+    private static bool AreClose(DateTimeOffset? expectedStartTime, DateTime processStartTime, TimeSpan? tolerance = default)
+    {
+        if (expectedStartTime is null)
+        {
+            return true;
+        }
+
+        tolerance ??= TimeSpan.FromMilliseconds(1);
```
Comment (mitchdenny) [inline src/Shared/ProcessSignaler.cs]: **Bug (Critical):** The 1ms default tolerance is too strict for callers that serialize start time as Unix *seconds* (`ToUnixTimeSeconds()`), which truncates the sub-second component.

Concrete trace for `CliOrphanDetector.IsProcessRunningWithStartTime`:
1. CLI serializes its start time: `Process.GetCurrentProcess().StartTime` -> e.g. `2026-04-10T01:15:20.456` -> `ToUnixTimeSeconds()` -> `1776048920` (sub-seconds lost)
2. AppHost reads it: `DateTimeOffset.FromUnixTimeSeconds(1776048920)` -> `2026-04-10T01:15:20.000Z`
3. `TryGetRunningProcess` reads `process.StartTime` -> `2026-04-10T01:15:20.456` (full precision)
4. `AreClose` computes: `|.000 - .456| = 456ms > 1ms` -> **returns false**

The old `CliOrphanDetector` code compared `ToUnixTimeSeconds()` on both sides (same precision, always matched). The new code via `TryGetRunningProcess` compares a seconds-precision `DateTimeOffset` against a sub-second-precision `DateTime`, failing ~99% of the time.

This breaks:
- **`CliOrphanDetector`**: always thinks CLI exited -> AppHost shuts down immediately as orphan
- **`StopCommand.SendStopSignal`** for CLI PID: `TryGetRunningProcess` returns null -> no graceful signal sent
- **`StopCommand.ForceKillProcess`** for CLI PID: silently skips force-kill

Fix: change the tolerance to `TimeSpan.FromSeconds(1)` to match the serialization precision, or convert both sides to Unix seconds before comparing (like the old code did).

File: src/Aspire.Cli/Commands/StopCommand.cs [hunk 6]
```diff
@@ -213,55 +208,55 @@ private async Task<int> StopAppHostAsync(IAppHostAuxiliaryBackchannel connection
...
                     _interactionService.DisplayError(StopCommandStrings.FailedToStopAppHost);
                     return ExitCodeConstants.FailedToDotnetRunAppHost;
                 }
             }
-            else if (!rpcSucceeded)
+            catch (Exception ex)
             {
-                _interactionService.DisplayError(StopCommandStrings.FailedToStopAppHost);
-                return ExitCodeConstants.FailedToDotnetRunAppHost;
+                _logger.LogWarning(ex, "Failed to send stop signal via RPC");
```
Comment (mitchdenny) [inline src/Aspire.Cli/Commands/StopCommand.cs]: **Bug (Medium):** When the RPC call throws, execution falls through to the monitoring section without any stop signal having been sent. Nothing requests the AppHost to stop, so the monitor waits for a process that was never asked to terminate, eventually timing out and force-killing.

The old code had a fallback to signal the AppHost PID directly when RPC failed. That fallback was removed, leaving a silent gap. Consider either:
- Returning an error (like the `!rpcSucceeded` path above does), or
- Re-adding a direct signal to the AppHost PID as a last resort

File: src/Aspire.Cli/Commands/StopCommand.cs [hunk 7]
```diff
@@ -286,28 +281,21 @@ private async Task<int> StopAppHostAsync(IAppHostAuxiliaryBackchannel connection
     }
 
     /// <summary>
-    /// Sends a stop signal to a process to terminate it and its process tree.
-    /// Uses Process.Kill(entireProcessTree: true) to ensure all child processes are terminated.
+    /// Sends a best-effort graceful shutdown signal to the target process.
+    /// Uses Ctrl-C on Windows and SIGTERM on non-Windows.
```
Comment (mitchdenny) [inline src/Aspire.Cli/Commands/StopCommand.cs]: **Nit:** Doc says "Uses Ctrl-C on Windows" but the code sends `CTRL_BREAK_EVENT` (value 1). Should say "Ctrl+Break".

**Review by mitchdenny — COMMENTED** [review]
Review of process signaling and stop command changes.

File: src/Aspire.Cli/Processes/DetachedProcessLauncher.Windows.cs [hunk 8]
```diff
@@ -77,16 +77,17 @@ private static Process StartWindows(string fileName, IReadOnlyList<string> argum
 
                     var si = new STARTUPINFOEX();
                     si.cb = Marshal.SizeOf<STARTUPINFOEX>();
-                    si.dwFlags = StartfUseStdHandles;
+                    si.dwFlags = StartfUseStdHandles | StartfUseShowWindow;
```
Comment (davidfowl) [inline src/Aspire.Cli/Processes/DetachedProcessLauncher.Windows.cs:80]: What does this do? Allow GUI apps to show up?

Comment (karolz-ms) [reply src/Aspire.Cli/Processes/DetachedProcessLauncher.Windows.cs:80]: Original code was setting `CreateNoWindow` flag; this was one of the changes that I made to make it possible to do a graceful shutdown by sending Ctrl-Break to the process console, but to be honest, I am not sure if it is strictly necessary vs keeping the old flag. We use this approach with window hiding in DCP to good effect, so there's that.

File: src/Shared/ProcessSignaler.cs (hunk 5 above)
Comment (karolz-ms) [reply src/Shared/ProcessSignaler.cs]: I guess it is true. Will change the default tolerance to 1 second

File: src/Aspire.Cli/Commands/StopCommand.cs (hunk 6 above)
Comment (karolz-ms) [reply src/Aspire.Cli/Commands/StopCommand.cs]: Yes that was my mistake, did not notice that the fallback on RPC failure was using the app host PID, not the cli PID. Will restore that part.

File: src/Aspire.Cli/Commands/StopCommand.cs (hunk 7 above)
Comment (karolz-ms) [reply src/Aspire.Cli/Commands/StopCommand.cs]: fixed

**Comment by davidfowl** [comment]
@karolz-ms can you add an end to end to test for this scenario. They all call stop right now but I guess we don't really assert anything after that.

**Comment by karolz-ms** [comment]
@davidfowl I changed existing test to ensure containers are being stopped by `aspire stop` command. With this change the same test would have failed without the fix in this PR. Let me know if you want me to do more than this.

**Comment by karolz-ms** [comment]
The current check might be too simplistic. I need to figure out something better i.e. ensure that the specific test container is cleaned up

**Review by davidfowl — APPROVED** [review]
Looks good! One minor nit:

`ProcessSignaler.ForceKill` has a small TOCTOU window — the process can exit between `TryGetRunningProcess` (which checks `HasExited`) and the subsequent `process.Kill()` call. If that happens, `Kill()` throws `InvalidOperationException`, which bubbles up through the `foreach` loop in `StopAppHostAsync` and gets caught by the outer `catch (Exception)` — resulting in a "failed to stop" error message even though the process did stop. The process always ends up dead either way, so this is cosmetic, but wrapping the `Kill()` in a try-catch would clean it up.
