### PR TITLE
Fix theme selection dialog

### LINKED ISSUE #6282: [WebToolsE2E][Aspire] The dashboard theme is set to light by default. After manually selecting the system theme, closing and reopening Settings, the theme is automatically set to light again.
**REGRESSION INFO**: Worked in Aspire 8.2.1

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0.100-rc.2.24474.11
3. Install Aspire 9.0 [9.0.0-preview.5.24513.1]

   - Add dotnet8 feed
   - dotnet new install Aspire.ProjectTemplates::9.0.0-preview.5.24513.1 --force

**REPRO STEPS**

1. Open CMD, run following command to create an Aspire Starter App project
```
dotnet new aspire-starter-9 -o AspireStarterApp
cd AspireStarterApp/AspireStarterApp.AppHost
```
2. Dotnet run the project in CMD, and open URL in the browser.
   `dotnet run`

**NOTE**: After manually selecting the dark theme, closing and reopening Settings, the theme is still dark.

**ACTUAL**:
The dashboard theme is set to light by default. After manually selecting the system theme, closing and reopening Settings, the theme is automatically set to light again.
Image

**EXPECTED**:
The dashboard theme is set to system by default. After manually selecting the system theme, close and reopen Settings, the theme is still system.

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

Selecting the system theme was lost. It would reset to select the light or dark theme depending on your system settings.

Fixes https://github.com/dotnet/aspire/issues/6282

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6325)

### CODE REVIEW

File: src/Aspire.Dashboard/Model/ThemeManager.cs [hunk 1]
```diff
@@ -6,24 +6,29 @@
...
+    public async Task<ThemeSettings> GetThemeSettingsAsync(CancellationToken cancellationToken)
     {
         if (_jsModule == null)
         {
             _jsModule = await _jsRuntime.InvokeAsync<IJSObjectReference>("import", "/js/app-theme.js").ConfigureAwait(false);
         }
 
-        return await _jsModule.InvokeAsync<string>("getCurrentTheme", cancellationToken).ConfigureAwait(false);
+        var currentTheme = await _jsModule.InvokeAsync<string>("getCurrentTheme", cancellationToken).ConfigureAwait(false);
+        var themeCookieValue = await _jsModule.InvokeAsync<string?>("getThemeCookieValue", cancellationToken).ConfigureAwait(false);
```
Comment (drewnoakes) [inline src/Aspire.Dashboard/Model/ThemeManager.cs:29]: Given this is a network call, perhaps they should run concurrently rather than serially.

```suggestion
        var currentThemeTask = _jsModule.InvokeAsync<string>("getCurrentTheme", cancellationToken).ConfigureAwait(false);
        var themeCookieValueTask = _jsModule.InvokeAsync<string?>("getThemeCookieValue", cancellationToken).ConfigureAwait(false);
        var currentTheme = await currentThemeTask;
        var themeCookieValue = await themeCookieValueTask;
```

File: src/Aspire.Dashboard/Model/ThemeManager.cs [hunk 2]
```diff
@@ -71,11 +77,15 @@ public string EffectiveTheme
...
-    public async Task EnsureEffectiveThemeAsync()
+    public async Task EnsureBrowserThemeLoadedAsync()
     {
-        if (_effectiveTheme == null)
+        if (!_hasLoaded)
         {
-            _effectiveTheme = await _effectiveThemeResolver.GetEffectiveThemeAsync(CancellationToken.None).ConfigureAwait(false);
+            var browserThemeSettings = await _themeResolver.GetThemeSettingsAsync(CancellationToken.None).ConfigureAwait(false);
+            _effectiveTheme = browserThemeSettings.EffectiveTheme;
+            SelectedTheme = !string.IsNullOrEmpty(browserThemeSettings.SelectedTheme) ? browserThemeSettings.SelectedTheme : null;
```
Comment (drewnoakes) [inline src/Aspire.Dashboard/Model/ThemeManager.cs:86]: Should the `SelectedTheme` getter be changed to throw if `!_hasLoaded`, similar to the getter for `EffectiveTheme`?

File: tests/Aspire.Dashboard.Components.Tests/Shared/TestThemeResolver.cs [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using Aspire.Dashboard.Model;
+
+namespace Aspire.Dashboard.Components.Tests.Shared;
+
+public sealed class TestThemeResolver : IThemeResolver
+{
+    public string EffectiveTheme { get; set; } = "Dark";
```
Comment (drewnoakes) [inline tests/Aspire.Dashboard.Components.Tests/Shared/TestThemeResolver.cs:10]: The rest of the code uses lowercase values here. I know this is test code, but better to be consistent.

```suggestion
    public string EffectiveTheme { get; set; } = "dark";
```

**Review by drewnoakes — APPROVED** [review]
