### PR TITLE
Reject invalid histogram data points

### LINKED ISSUE #6962: micrometer http.server.requests metric breaks metrics UI with IndexOutOfRangeException
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

with a http.server.requests metric exported via the otel agent's micrometer bridge, the aspire dashboard can get into an odd state .

if I navigate to the micrometer metric http.server.requests, I get an IndexOutOfRangeException in the aspire dashboard's container logs.

standalone aspire dashboard started with: 
```shell
docker run --rm -it -p 8000:18888 -p 4317:18889 -p 4318:18890 --name aspire-dashboard -e DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS="true" mcr.microsoft.com/dotnet/aspire-dashboard
```

enabled micrometer metrics bridge with :
`otel.instrumentation.micrometer.enabled=true` in my JVM settings

I can navigate via the left-nav to logs or traces, and the UI is responsive.
If I navigate back to metrics, the UI is unresponsive. I am unable to select other metrics.

In the browser window, I have to manually remove the query parameters from the URI, and then navigate to 

for example, change from this: 
```
http://localhost:8000/metrics/resource/my-application-name?meter=io.opentelemetry.micrometer-1.5&instrument=http.server.requests&duration=5
```
to 
```
http://localhost:8000/metrics/resource/my-application-name
```

once I manually remove those query parameters, I can select other (non-micrometer) metrics in the UI  

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Index was outside the bounds of the array.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.CalculatePercentile(Int32 percentile, UInt64[] counts, Double[] explicitBounds) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 346
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.TryCalculateHistogramPoints(List`1 dimensions, DateTimeOffset start, DateTimeOffset end, Dictionary`2 traces, List`1 exemplars) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 276
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.CalculateHistogramValues(List`1 dimensions, Int32 pointCount, Boolean tickUpdate, DateTimeOffset inProgressDataTime, String yLabel) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 147
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.UpdateChartAsync(Boolean tickUpdate, DateTimeOffset inProgressDataTime) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 506
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.OnAfterRenderAsync(Boolean firstRender) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 107
         at Aspire.Dashboard.Components.PlotlyChart.OnAfterRenderAsync(Boolean firstRender) in /_/src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs:line 177
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '2YmzVDSrBI8PnW2kK1Vw-iP_YeL1r-p14788V170uBw'.
      System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
       ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.CalculatePercentile(Int32 percentile, UInt64[] counts, Double[] explicitBounds) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 346
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.TryCalculateHistogramPoints(List`1 dimensions, DateTimeOffset start, DateTimeOffset end, Dictionary`2 traces, List`1 exemplars) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 276
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.CalculateHistogramValues(List`1 dimensions, Int32 pointCount, Boolean tickUpdate, DateTimeOffset inProgressDataTime, String yLabel) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 147
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.UpdateChartAsync(Boolean tickUpdate, DateTimeOffset inProgressDataTime) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 506
         at Aspire.Dashboard.Components.Controls.Chart.ChartBase.OnAfterRenderAsync(Boolean firstRender) in /_/src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs:line 107
         at Aspire.Dashboard.Components.PlotlyChart.OnAfterRenderAsync(Boolean firstRender) in /_/src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs:line 177
         --- End of inner exception stack trace ---

### .NET Version info

_No response_

### Anything else?

aspire dashboard 9.0.0 (standalone)

otel java agent 2.10.0

java app - spring boot 3.4.0, temurin java 21.0.1
configured for jetty, not tomcat.

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

Fixes https://github.com/dotnet/aspire/issues/6962

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6998)

### CODE REVIEW

File: src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs [hunk 1]
```diff
@@ -68,13 +70,17 @@ public void AddMetrics(AddContext context, RepeatedField<ScopeMetrics> scopeMetr
...
                         };
 
-                        instrument.AddMetrics(metric, ref tempAttributes);
+                        instrument = instrumentRef;
                     }
                     catch (Exception ex)
                     {
-                        context.FailureCount++;
-                        Context.Logger.LogInformation(ex, "Error adding metric.");
+                        // If we can't create the instrument then all data points for it are failures.
```
Comment (eerhardt) [inline src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs:77]: What happens if this was the case that added the key to `_instruments` and then it failed? Does the entry need to get removed from the dictionary?

Comment (JamesNK) [reply src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs:77]: An empty graph is displayed if the instrument was added but all its data points failed. I think that's fine.

File: src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs [hunk 2]
```diff
@@ -68,13 +70,17 @@ public void AddMetrics(AddContext context, RepeatedField<ScopeMetrics> scopeMetr
...
+                        context.FailureCount += GetMetricDataPointCount(metric);
+                        Context.Logger.LogInformation(ex, "Error adding metric instrument {MetricName}.", metric.Name);
+                        return;
```
Comment (eerhardt) [inline src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs:80]: Is it OK to skip the metrics coming after this invalid one? Or should this be:

```suggestion
                        continue;
```

**Review by eerhardt — APPROVED** [review]
Just one more question.
