### PR TITLE
make non-http panel links non-clickable

### LINKED ISSUE #15472: VS Code extension shouldn't offer to open non HTTP resources in browser
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you have a SQL Container resource (in this case `SqlServerEndToEnd` playground app), VS Code offers to let you open the primary endpoint in your browser.  But that doesn't make sense for a non HTTP endpoint.

Image

### Expected Behavior

The "open in browser" / "open in VSCode" links probably shouldn't show unless the scheme is http/https.

### Steps To Reproduce

1. Run the `SqlServerEndToEnd` playground project in VS Code
2. Look at a SQL Server resource. 

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamint**
## Description

Fixes #15472

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [X] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to `aspire.dev` issue:
      - [New issue](https://github.com/microsoft/aspire.dev/issues/new)
  - [X] No

### CODE REVIEW

File: extension/src/views/AspireAppHostTreeProvider.ts [hunk 1]
```diff
@@ -79,14 +79,21 @@ class PidItem extends vscode.TreeItem {
...
-        this.iconPath = new vscode.ThemeIcon('link-external');
         this.tooltip = url;
-        this.contextValue = 'endpointUrl';
-        this.command = {
-            command: 'vscode.open',
-            title: url,
-            arguments: [vscode.Uri.parse(url)]
-        };
+
+        const isHttpUrl = url.startsWith('http://') || url.startsWith('https://');
```
Comment (JamesNK) [inline extension/src/views/AspireAppHostTreeProvider.ts]: Does this need to worry about case? i.e. `HTTP://`

Comment (adamint) [reply extension/src/views/AspireAppHostTreeProvider.ts]: Yea, it should be case insensitive. Updated

**Review by JamesNK — APPROVED** [review]

**Comment by JamesNK** [comment]
Actually, I don't think this is the right fix. There are cases where people want non-http links to be clickable. For example, `vscode://` links that then activate VS Code.

The dashboard has a deny list - s_browserUnsupportedSchemes - for explicitly not making some endpoints clickable. I suggest the extension does the same thing.
