### PR TITLE
Show neutral icon for container exiting with status code 0

### LINKED ISSUE #6785: Exe and Container reaching Exit Code 0 have different terminal states for the same result.
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you have a container that exists with exit code 0 (Think of a Kubernetes job that runs to completion successfully), aspire reports this as `Exited` and  shows up as a warning.  When an executable does the same thing, it instead goes to neutral state.

Similarly for a container with an exit code, it ends up in the `Exited` state whilst an executable ends up in the `Finished` state

Image

### Expected Behavior

I'd expect the two Green highlighted fields to be in the same `Finished` state with a neutral icon.  I'd expect the two blue highlighted fields to end up in the same `Finished` state with an error icon.

Image

### Steps To Reproduce

```cs
var successExe = builder.AddExecutable("successExe", "pwsh.exe", ".")
    .WithArgs("-Command", "Write-Host Success");
var failExe = builder.AddExecutable("failExe", "pwsh.exe", ".")
    .WithArgs("-Command", "throw fail");

var successContainer = builder.AddContainer("successContainer", "mcr.microsoft.com/powershell")
    .WithArgs("pwsh", "-Command", "Write-Host Success");
var failContainer = builder.AddContainer("failContainer", "mcr.microsoft.com/powershell")
    .WithArgs("pwsh", "-Command", "throw Fail");
```

### Exceptions (if any)

_No response_

### .NET Version info

```
.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

.NET workloads installed:
 [aspire]
   Installation Source: VS 17.12.35514.174
   Manifest Version:    8.2.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.2\WorkloadManifest.json
   Install Type:              Msi

Configured to use loose manifests when installing new manifests.

Host:
  Version:      9.0.0
  Architecture: x64
  Commit:       9d5a6a9aa4

.NET SDKs installed:
  6.0.428 [C:\Program Files\dotnet\sdk]
  8.0.404 [C:\Program Files\dotnet\sdk]
  9.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Anything else?

```xml
		<Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />
		<PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
```

### PR DESCRIPTION
**Pull request by adamint**
## Description

Fixes #6785

image

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [X] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [X] No

### CODE REVIEW

File: src/Aspire.Dashboard/Model/ResourceStateViewModel.cs [hunk 1]
```diff
@@ -42,7 +42,7 @@ private static (Icon icon, Color color) GetStateIcon(ResourceViewModel resource)
                 icon = new Icons.Filled.Size16.ErrorCircle();
                 color = Color.Error;
             }
-            else if (resource.IsFinishedState())
+            else if (resource.TryGetExitCode(out _) && (resource.IsFinishedState() || resource.IsExitedState()))
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/ResourceStateViewModel.cs:45]: What is TryGetExitCode here for?

Comment (JamesNK) [reply src/Aspire.Dashboard/Model/ResourceStateViewModel.cs:45]: For example,

image

**Comment by davidfowl** [comment]
I think we should unify exited and finished. I'm not sure why we have both.

**Comment by adamint** [comment]
> I think we should unify exited and finished. I'm not sure why we have both.

@mitchdenny @karolz-ms ?

**Comment by karolz-ms** [comment]
In DCP Containers are `Exited`, and Executables are `Finished` at the end. It is just the way the world is 🤷‍♂️ 😄 

Executables can also be `Terminated`, but that is related to replica sets which Aspire is not using anymore. And I have a bug to fix where Executables managed by an IDE go into `Terminated` state at the end; they should be `Finished` instead. It was supposed to be fixed in 9.2 but I ran out of time.

**Comment by JamesNK** [comment]
I'm ok with making them consistent. `Exited` would be the logic choice for use for both. And it lines up with exit codes.

**Review by JamesNK — APPROVED** [review]
