### PR TITLE
Give theme cookie an expiration

### LINKED ISSUE #5430: Persist dashboard theme
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The dashbaord theme is set into a cookie. PR https://github.com/dotnet/aspire/pull/5429 gives that cookie a 1 year expiration. But the theme is still forgotten one year after it is set.

### Expected Behavior

We want a sliding expiration, e.g. remember the cookie for 1 year after the dashboard was last launched.

When the dashboard starts it should check if there is a theme cookie set, and reapply it with a new expiration.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

I noticed that Aspire dashboard sometimes lost the theme. The reason is the theme cookie had a session lifetime. Once all browsers are closed the cookie is cleared and the dashboard forgets the configured theme.

This PR:

* Gives the cookie a 1 year expiration
* If the theme cookie is present when the dashboard loads, it is set again to create a sliding expiration (i.e. cookie expires 1 year after the dashboard was last loaded)
* Specifies a path when working with the cookie to be explicit about where it is set
* Deletes the cookie if "System" is selected in the UI. No point having a cookie set and updating it if it is the default value.

image

Fixes https://github.com/dotnet/aspire/issues/5430

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5429)

### CODE REVIEW

File: src/Aspire.Dashboard/wwwroot/js/app-theme.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ export function updateTheme(specifiedTheme) {
  * @returns {string}
  */
 export function getThemeCookieValue() {
-    return getCookieValue(currentThemeCookieName) ?? themeSettingSystem;
```
Comment (drewnoakes) [inline src/Aspire.Dashboard/wwwroot/js/app-theme.js:38]: The comment on this method is no longer correct with this change.

Comment (drewnoakes) [inline src/Aspire.Dashboard/wwwroot/js/app-theme.js:38]: Looks like `themeSettingSystem` is no longer used and can be removed.

**Review by drewnoakes — APPROVED** [review]
