### PR TITLE
Template tests: Add retries to handle browser failures

### LINKED ISSUE #8191: Flaky test: StarterTemplateWithRedisCacheTests_PreviousTFM.ApiServiceWorks - `net::ERR_NETWORK_CHANGED`
https://github.com/dotnet/aspire/actions/runs/13958419016/job/39074954262?pr=8189

I've seen this test fail about 3-4 times now in PRs:

Disabled in: #8189

Snippet of build logs to help with diagnostics:

```
[xUnit.net 00:05:12.23] Aspire.Workload.Tests: [Long Running Test] 'Aspire.Workload.Tests.StarterTemplateWithRedisCacheTests_PreviousTFM.ApiServiceWorks(urlPrefix: "http://")', Elapsed: 00:03:50
[xUnit.net 00:06:24.01]     Aspire.Workload.Tests.StarterTemplateWithRedisCacheTests_PreviousTFM.ApiServiceWorks(urlPrefix: "http://") [OUTPUT] Dashboard screenshot saved to /home/runner/work/aspire/aspire/artifacts/log/test-logs/aspire-starter_net8.0_uo2nx3xy_lp5/dashboard-fail.png
[xUnit.net 00:06:24.03]     Aspire.Workload.Tests.StarterTemplateWithRedisCacheTests_PreviousTFM.ApiServiceWorks(urlPrefix: "http://") [FAIL]
[xUnit.net 00:06:24.03]       Expected rows not found: apiservice, webfrontend, cache
[xUnit.net 00:06:24.03]       Stack Trace:
[xUnit.net 00:06:24.03]         /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs(280,0): at Aspire.Workload.Tests.WorkloadTestsBase.CheckDashboardHasResourcesActualAsync(IPage dashboardPage, IEnumerable`1 expectedResources, ITestOutputHelper testOutput, Int32 timeoutSecs)
[xUnit.net 00:06:24.03]         /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs(153,0): at Aspire.Workload.Tests.WorkloadTestsBase.CheckDashboardHasResourcesAsync(IPage dashboardPage, IEnumerable`1 expectedResources, ITestOutputHelper testOutput, String logPath, Int32 timeoutSecs)
[xUnit.net 00:06:24.03]         /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs(160,0): at Aspire.Workload.Tests.WorkloadTestsBase.CheckDashboardHasResourcesAsync(IPage dashboardPage, IEnumerable`1 expectedResources, ITestOutputHelper testOutput, String logPath, Int32 timeoutSecs)
[xUnit.net 00:06:24.03]         /_/tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs(63,0): at Aspire.Workload.Tests.StarterTemplateRunTestsBase`1.ApiServiceWorks(String urlPrefix)
[xUnit.net 00:06:24.03]         /_/tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs(71,0): at Aspire.Workload.Tests.StarterTemplateRunTestsBase`1.ApiServiceWorks(String urlPrefix)
[xUnit.net 00:06:24.03]         --- End of stack trace from previous location ---
[xUnit.net 00:06:24.03]       Output:
[xUnit.net 00:06:24.03]         Waiting for resources to appear on the dashboard
[xUnit.net 00:06:24.03]         Dashboard screenshot saved to /home/runner/work/aspire/aspire/artifacts/log/test-logs/aspire-starter_net8.0_uo2nx3xy_lp5/dashboard-fail.png
  Failed Aspire.Workload.Tests.StarterTemplateWithRedisCacheTests_PreviousTFM.ApiServiceWorks(urlPrefix: "http://") [5 m 1 s]
  Error Message:
   Expected rows not found: apiservice, webfrontend, cache
  Stack Trace:
     at Aspire.Workload.Tests.WorkloadTestsBase.CheckDashboardHasResourcesActualAsync(IPage dashboardPage, IEnumerable`1 expectedResources, ITestOutputHelper testOutput, Int32 timeoutSecs) in /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs:line 280
   at Aspire.Workload.Tests.WorkloadTestsBase.CheckDashboardHasResourcesAsync(IPage dashboardPage, IEnumerable`1 expectedResources, ITestOutputHelper testOutput, String logPath, Int32 timeoutSecs) in /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs:line 153
   at Aspire.Workload.Tests.WorkloadTestsBase.CheckDashboardHasResourcesAsync(IPage dashboardPage, IEnumerable`1 expectedResources, ITestOutputHelper testOutput, String logPath, Int32 timeoutSecs) in /_/tests/Aspire.Workload.Tests/WorkloadTestsBase.cs:line 160
   at Aspire.Workload.Tests.StarterTemplateRunTestsBase`1.ApiServiceWorks(String urlPrefix) in /_/tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs:line 63
   at Aspire.Workload.Tests.StarterTemplateRunTestsBase`1.ApiServiceWorks(String urlPrefix) in /_/tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs:line 71
--- End of stack trace from previous location ---
  Standard Output Messages:
 Waiting for resources to appear on the dashboard
 Dashboard screenshot saved to /home/runner/work/aspire/aspire/artifacts/log/test-logs/aspire-starter_net8.0_uo2nx3xy_lp5/dashboard-fail.png



Error: Expected rows not found: apiservice, webfrontend, cache
```

### PR DESCRIPTION
**Pull request by radical**
Template tests: Reload playwright page if it fails to load

Loading the page can sometimes fail with errors like
`[browser-console] Failed to load resource: net::ERR_NETWORK_CHANGED`,
or the websocket getting disconnected, causing the tests to fail. This
commit add retries for such cases.

Fixes https://github.com/dotnet/aspire/issues/8191

### CODE REVIEW

File: tests/Shared/TemplatesTesting/AspireProject.cs [hunk 1]
```diff
@@ -337,10 +337,30 @@ public async Task<IPage> OpenDashboardPageAsync(IBrowserContext context, int tim
         cts.CancelAfter(TimeSpan.FromSeconds(DashboardAvailabilityTimeoutSecs));
         await WaitForDashboardToBeAvailableAsync(dashboardUrlToUse, _testOutput, cts.Token).ConfigureAwait(false);
 
-        var dashboardPage = await context.NewPageWithLoggingAsync(_testOutput);
-        await dashboardPage.GotoAsync(dashboardUrlToUse);
+        var dashboardPageWrapper = await context.NewPageWithLoggingAsync(_testOutput);
+        var maxRetryAttempts = 3;
+        var numAttempts = 0;
+        while (true)
```
Comment (eerhardt) [inline tests/Shared/TemplatesTesting/AspireProject.cs:343]: Would it make sense to use Polly here?

**Review by eerhardt — APPROVED** [review]
LGTM
