### PR TITLE
Fix localized built-in command display names and descriptions

### LINKED ISSUE #8946: [WebToolsE2E][Aspire] In the Aspire Dashboard the restart/start/stop buttons and some words in the setting pane isn't localized on non-ENU OS.
**REGRESSION INFO**

Worked in Aspire 9.2.1 

**INSTALL STEPS**

1. Clean machine: Win11 x64 23h2 ENU
2. Install SDK 9.0.203
3. Add the dotnet9 feed for 9.3.0-preview.1
4. Install the latest Aspire 9.3.0-preview.1 templates
`dotnet new install Aspire.ProjectTemplates::9.3.0-preview.1.25223.6 `

**NOTE**
1. This issue also reproduce using the "aspire new" command.

**REPRO STEPS**

1. Run the command in the CMD.
```
dotnet new aspire-starter -o aspire
cd aspire
cd aspire.apphost
```
2. Run the project using this command:
`dotnet run`
3. In the Setting Pane on the Aspire Dashboard, click different language.

**ACTUAL**
The start/stop/restart button isn't localized in the Resources Page.
Image
Image

In the Graph Table
Image

In the Settings Pane
The "Resource logs and Telemetry" are not localized.
Image

When hovering the buttons it isn't localize either.
Image

**EXPECTED**
It should be localized to different languages.

### PR DESCRIPTION
**Pull request by adamint**
## Description

I made a mistake in the initial workaround for these commands. Since the resource subscription isn't tied to individual requests, the display name/description interception logic needs to be done when those fields are actually being queried.

Fixes #8946

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [X] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue (consider using one of the following templates):
      - [New (or update) `doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)
      - [New `breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)
      - [New `diagnostic` template](https://github.com/dotnet/docs-aspire/issues/new?template=06-diagnostic-addition.yml)
  - [X] No

### CODE REVIEW

File: src/Aspire.Dashboard/Model/ResourceViewModel.cs [hunk 1]
```diff
@@ -166,8 +168,35 @@ public sealed class CommandViewModel
...
+        {
+            return Name switch
+            {
+                KnownResourceCommands.StartCommand => Commands.StartCommandDisplayDescription,
+                KnownResourceCommands.StopCommand => Commands.StopCommandDisplayDescription,
+                KnownResourceCommands.RestartCommand => Commands.RestartCommandDisplayDescription,
+                _ => field
+            };
+        }
+    }
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/ResourceViewModel.cs:198]: We want to access resource translations via IStringLocalizer.

Can you change these to methods to methods that have an `IStringLocalizer<Commands>` parameter. Then whoever uses them is responsible for passing the localizer

**Comment by JamesNK** [comment]
I think this bug started when I change the dashboard client to a singleton instead of being tied to a session.

**Review by JamesNK — APPROVED** [review]
