### PR TITLE
Fix small metrics mobile issues left over after responsive changes

### LINKED ISSUE #5353: Metrics screen mobile issues
Metrics issues:

- [ ] This link doesn't have a pointer cursor on mouse over:
    image

- [ ] Same issue with the link below. Should it have the same position as the previous message? It feels odd to have the two links presented in different ways:
    image

- [ ] Changing the resource in the metrics filter view causes it to close. This is inconsistent with all the other filter views which stay open when a resource is selected.

- [ ] It feels weird that selecting an instrument or meter on the filter view doesn't immediately close the filter view and select the instrument/meter. Every time I come back to this filter view, it takes me a second of clicking the tree view multiple times to realise that I have to click the close button to see the selected item. I'd be curious what other people think here.

### PR DESCRIPTION
**Pull request by adamint**
## Description

Fixes #5353

- Adds cursor pointer to all links, regardless of whether they have an href
- Moves the "Select instrument" text to the same position as select resource on mobile
- The filter dialog closes immediately after selecting an instrument/metric
- The filter dialog does NOT close immediately after changing the instrument, and the list of available instruments/metrics are recomputed in the dialog

https://github.com/user-attachments/assets/e6758b90-b6a5-47a5-9586-f7d0f75822cb

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [X] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [X] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/6198)

### CODE REVIEW

File: src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs [hunk 1]
```diff
@@ -55,12 +55,17 @@ public static class PageExtensions
     /// <summary>
     /// Called after a change in the view model that will affect the url associated with new page state
     /// to navigate to the new url and save new state in localstorage.
+    ///
+    /// <param name="page"></param>
+    /// <param name="layout"></param>
+    /// <param name="waitToApplyChange">Whether we should avoid applying this change immediately, and instead
```
Comment (adamint) [inline src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:61]: changed this parameter name, so it now is more descriptive of the actual behavior

File: src/Aspire.Dashboard/Components/Controls/TreeMetricSelector.razor [hunk 2]
```diff
@@ -1,8 +1,30 @@
...
+    // this is because we have not updated the URL, which would close the details panel
+    // because of this, we should always compute the instruments from the repository
+    var selectedInstance = PageViewModel.SelectedApplication.Id?.GetApplicationKey();
+
+    if (selectedInstance is null)
+    {
+        return;
+    }
+
+    var instruments = TelemetryRepository.GetInstrumentsSummaries(selectedInstance.Value);
```
[the remark this answers is not in the document]
Comment (JamesNK) [reply src/Aspire.Dashboard/Components/Controls/TreeMetricSelector.razor:17]: What about instead:
1. Have SelectedApplication and its own parameter.
2. When the app parameter changes, the instruments can be updated in `OnParametersSet`.

File: src/Aspire.Dashboard/Components/Controls/TreeMetricSelector.razor [hunk 3]
```diff
@@ -20,4 +42,15 @@
...
+    [Parameter]
+    public bool IncludeLabel { get; set; }
+
+    [Inject]
+    public required TelemetryRepository TelemetryRepository { get; init; }
+
+    public void OnResourceChanged()
+    {
+        StateHasChanged();
+    }
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Controls/TreeMetricSelector.razor:55]: Move this to code behind

File: src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs [hunk 4]
```diff
@@ -55,12 +55,17 @@ public static class PageExtensions
     /// <summary>
     /// Called after a change in the view model that will affect the url associated with new page state
     /// to navigate to the new url and save new state in localstorage.
+    ///
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:58]:
```suggestion
```

File: src/Aspire.Dashboard/Components/Pages/Metrics.razor [hunk 5]
```diff
@@ -107,10 +111,12 @@
                                         }
                                         else
                                         {
-                                            // class needed to prevent color from being removed from reboot style
-                                            <a class="" @onclick="@(async () => await _contentLayout!.OpenMobileToolbarAsync())">
-                                                @Loc[nameof(Dashboard.Resources.Metrics.MetricsSelectInstrument)]
-                                            </a>
+                                            <div class="empty-content">
+                                                <!-- class needed to prevent color from being removed from reboot style -->
+                                                <a class="" @onclick="@(async () => await _contentLayout!.OpenMobileToolbarAsync())">
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/Metrics.razor:116]: Use FluentAnchor

See https://www.fluentui-blazor.net/Anchor and the `Link with no Href` example.

File: src/Aspire.Dashboard/wwwroot/css/app.css [hunk 6]
```diff
@@ -652,3 +652,7 @@ fluent-data-grid-cell.no-ellipsis {
     column-gap: 4px;
     align-items: center;
 }
+
+a:hover {
```
Comment (JamesNK) [inline src/Aspire.Dashboard/wwwroot/css/app.css:656]: Can remove. Use FluentAnchor.

File: src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs [hunk 7]
```diff
@@ -167,10 +169,8 @@ private Task HandleSelectedApplicationChangedAsync()
             }
         }
 
-        // On mobile, we actually *do* want to update the selected application immediately, since it will affect the tree of possible
-        // metrics to select from. So, we must also immediately close the window since the closing behavior is necessary if the url has changed.
-        var isChangeInToolbar = ViewportInformation.IsDesktop;
-        return this.AfterViewModelChangedAsync(_contentLayout, isChangeInToolbar: isChangeInToolbar);
+        await this.AfterViewModelChangedAsync(_contentLayout, waitToApplyMobileChange: true);
+        _treeMetricSelector?.OnResourceChanged();
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:173]: Do we need to call StateHasChanged on component or could StateHasChanged be called here?

Comment (adamint) [reply src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:173]: Unfortunately, calling  `StateHasChanged` on Metrics doesn't work, since this is in a render fragment inside a different component. That was the motivation initially behind the ref

**Comment by JamesNK** [comment]
@adamint I tested and found an issue with selecting the initially selected resource not working. Added a fix.

**Comment by JamesNK** [comment]
There are some test failures. Route parameter binding isn't working in the tests and I've asked the bunit folks for help. If there isn't feedback soon then I'll figure out a workaround to get the test working.

**Review by JamesNK — APPROVED** [review]
