### PR TITLE
Fix migrations service in playground

### LINKED ISSUE #2308: Error execute migration in playground DatabaseMigration service
Issue when starting the DatabaseMigration playground introduced in #2263.

First run when database does not exists the BeginTransactionAsync(..) stop further execution and no migration is applied.
```csharp
await strategy.ExecuteAsync(async () =>
{
    await using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken);
    await dbContext.Database.MigrateAsync(cancellationToken);
    await transaction.CommitAsync(cancellationToken);
});
```

With the following hack/workaround i managed to get around it and migrate the database:
```csharp
var appliedMigrations = await dbContext.Database.GetAppliedMigrationsAsync(cancellationToken);
if (!appliedMigrations.Any())
{
    await dbContext.Database.MigrateAsync(cancellationToken);
}
else
{
    await using var transaction = await dbContext.Database.BeginTransactionAsync(cancellationToken);
    await dbContext.Database.MigrateAsync(cancellationToken);
    await transaction.CommitAsync(cancellationToken);
}
```
Would be nice to know how this should be solved or if I missed something causing the issue.
I also experienced this in own application when apply same strategy mentioned in;
https://github.com/dotnet/aspire/pull/2263#discussion_r1492825290

```
Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot open database "db1" requested by the login. The login failed.
Login failed for user 'sa'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.InternalOpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(IsolationLevel isolationLevel, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at DatabaseMigration.MigrationService.ApiDbInitializer.<>c__DisplayClass6_0.<<InitializeDatabaseAsync>b__0>d.MoveNext() in C:\dev\aspire\playground\DatabaseMigration\DatabaseMigration.MigrationService\ApiDbInitializer.cs:line 34
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<<ExecuteAsync>b__3_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.<>c__DisplayClass30_0`2.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
ClientConnectionId:e4bea062-527b-4038-913f-da36f56f3c9b
Error Number:4060,State:1,Class:11

```

### PR DESCRIPTION
**Pull request by JamesNK**
Fixes https://github.com/dotnet/aspire/issues/2308

Creating a transaction failed if starting from a blank slate because there isn't a database to create a transaction on. Removing the transaction fixes this problem.

However, it would be ideal to keep the transaction to make this safe to transient errors. To follow best practice, we need to:
1. Create the database
2. Start transaction
3. Apply migratio
4. Commit transaction.

@AndriySvyryd How do you instruct EF to just create the database? I looked at `DbContext.Database.EnsureCreatedAsync`, but it also creates tables.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/2351)

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
You can call `dbContext.GetService<IRelationalDatabaseCreator>().CreateAsync()`

If you remove the transaction you'll need to remove the execution strategy as well as retrying in case of a failure will only make it worse. This is tracked in https://github.com/dotnet/efcore/issues/22616

**Comment by JamesNK** [comment]
The retry is there to keep retrying until the database server container is running.

I've re-added the transaction. Please take another look.

File: playground/DatabaseMigration/DatabaseMigration.MigrationService/ApiDbInitializer.cs [hunk 1]
```diff
@@ -18,19 +20,29 @@ protected override async Task ExecuteAsync(CancellationToken cancellationToken)
...
+        // Database container might not be ready yet, so we need to retry.
         var strategy = dbContext.Database.CreateExecutionStrategy();
         await strategy.ExecuteAsync(async () =>
         {
+            // Create the database if it does not exist.
+            // Do this first so there is then a database to start a transaction against.
+            if (!await dbCreator.ExistsAsync(cancellationToken))
+            {
+                await dbCreator.CreateAsync(cancellationToken);
+            }
```
Comment (AndriySvyryd) [inline playground/DatabaseMigration/DatabaseMigration.MigrationService/ApiDbInitializer.cs:43]: I'd move these to a separate `.ExecuteAsync` call, since they could use up all retries while waiting for the service to start and if there's any delay creating the database `BeginTransactionAsync` will just fail without retrying.

**Review by AndriySvyryd — APPROVED** [review]
