### PR TITLE
Fix dotnet watch.

### LINKED ISSUE #1903: Reduce noise from inner host in AppHost console logs
From David's logs:

```
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) '
http://localhost:15085'.
Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on:
http://127.0.0.1:62049/
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\davifowl\source\repos\AppHost2\AppHost2
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\davifowl\source\repos\AppHost2\AppHost2
```

The kestrel warning shouldn't be here and we should only have content root once.

### LINKED ISSUE #1918: Regression: dotnet watch launches the GRPC server instead of the dashboard
Dotnet watch launches the grpc server instead of the dashboard because of the output of the apphost.

Should be fixed when https://github.com/dotnet/aspire/issues/1903 is fixed.

### PR DESCRIPTION
**Pull request by mitchdenny**
Fixes #1903 
Fixes #1918 

Related #1922

In this PR I suppress the kestrel and lifetime messages and output my own `Now listening on: ...` message to support `dotnet watch` browser launch. I also noticed that the manifest exclusion for the dashboard resources in our repos were removed when I moved code from the dashboard lifecycle hook I had previously implemented into the application executor. Rather than implement another hook I just added the manifest exclusions into our playground projects.

~~Note that there is an issue in our repo right now where dotnet watch does not seem to set the launch profile correctly so I am having trouble testing this change in the repo itself. We may need to figure that out before we can safely merge this change.~~

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/1933)

### CODE REVIEW

File: playground/orleans/OrleansAppHost/Program.cs [hunk 1]
```diff
@@ -23,7 +23,7 @@
 // to test end developer dashboard launch experience. Refer to Directory.Build.props
 // for the path to the dashboard binary (defaults to the Aspire.Dashboard bin output
 // in the artifacts dir).
-builder.AddProject<Projects.Aspire_Dashboard>(KnownResourceNames.AspireDashboard);
+builder.AddProject<Projects.Aspire_Dashboard>(KnownResourceNames.AspireDashboard).ExcludeFromManifest();
```
Comment (davidfowl) [inline playground/orleans/OrleansAppHost/Program.cs:26]: This should be special logic applied to the known resource name.

File: playground/mongo/Mongo.AppHost/Properties/launchSettings.json [hunk 2]
```diff
@@ -5,12 +5,12 @@
       "commandName": "Project",
       "dotnetRunMessages": true,
       "launchBrowser": true,
-      "applicationUrl": "http://localhost:15888",
+      "applicationUrl": "http://localhost:15888/",
```
Comment (davidfowl) [inline playground/mongo/Mongo.AppHost/Properties/launchSettings.json:8]: Why this change?

File: src/Aspire.Hosting/DistributedApplication.cs [hunk 3]
```diff
@@ -121,29 +155,34 @@ public async Task StopAsync(CancellationToken cancellationToken = default)
         await _host.StopAsync(cancellationToken).ConfigureAwait(false);
     }
 
-    private void SuppressLifetimeLogsDuringManifestPublishing()
+    private void SuppressLogs()
```
Comment (davidfowl) [inline src/Aspire.Hosting/DistributedApplication.cs:158]: Can we clean up the log suppression to do what the dashboard does?

File: playground/orleans/OrleansAppHost/Program.cs (hunk 1 above)
Comment (mitchdenny) [reply playground/orleans/OrleansAppHost/Program.cs:26]: I used to do this when I had the lifecycle hook but we moved the logic. I'll add a new lifecycle hook back in. We can't exclude from the manifest where we moved it to (it's too late).

File: playground/mongo/Mongo.AppHost/Properties/launchSettings.json (hunk 2 above)
Comment (mitchdenny) [reply playground/mongo/Mongo.AppHost/Properties/launchSettings.json:8]: I'll revert. Was doing some experimentation with a dotnet watch "bug" / "feature"

File: playground/orleans/OrleansAppHost/Program.cs (hunk 1 above)
Comment (davidfowl) [reply playground/orleans/OrleansAppHost/Program.cs:26]: Just add logic to the manifest generator to leave out this resource. It doesn't need to be a hook.

File: src/Aspire.Hosting/DistributedApplication.cs [hunk 4]
```diff
@@ -121,29 +155,34 @@ public async Task StopAsync(CancellationToken cancellationToken = default)
...
         var hostingLifetimeLoggingLevelSection = config.GetSection("Logging:LogLevel:Microsoft.Hosting.Lifetime");
         hostingLifetimeLoggingLevelSection.Value = "Warning";
 
+        // Suppresses warning that we've overridden the default ASPNETCORE_URLS value. This is
+        // because the endpoints that we host in the AppHost is a randomly assinged resource
+        // endpoint that is used for the dashboard. The ASPNETCORE_URLS value is actually passed
+        // into the dashboard that is launched out of process.
+        var aspNetCoreServerKestrelLoggingLevelSection = config.GetSection("Logging:LogLevel:Microsoft.AspNetCore.Server.Kestrel");
+        aspNetCoreServerKestrelLoggingLevelSection.Value = "None";
+
```
Comment (davidfowl) [inline src/Aspire.Hosting/DistributedApplication.cs:176]: We should do this in the resource server logic instead of the above.

https://github.com/dotnet/aspire/blob/7e4a7cc701bf8291ca606cefcdf860ea4eebad53/src/Aspire.Dashboard/DashboardWebApplication.cs#L29-L30

Comment (mitchdenny) [reply src/Aspire.Hosting/DistributedApplication.cs:176]: Should be able to do that.

File: playground/orleans/OrleansAppHost/Program.cs (hunk 1 above)
Comment (davidfowl) [reply playground/orleans/OrleansAppHost/Program.cs:26]: Maybe lower tech is just shared code.. in these playground projects that do this...

Comment (mitchdenny) [reply playground/orleans/OrleansAppHost/Program.cs:26]: Shared code doesn't help because you still have to invoke it from somewhere. I'll add some exclusion logic to the manifest generator. Although TBH its just a hack, the better approach is a hook.

File: playground/mongo/Mongo.AppHost/Properties/launchSettings.json (hunk 2 above)
Comment (mitchdenny) [reply playground/mongo/Mongo.AppHost/Properties/launchSettings.json:8]: Was just experimenting with some behaviors in `dotnet watch`.

File: playground/orleans/OrleansAppHost/Program.cs (hunk 1 above)
Comment (davidfowl) [reply playground/orleans/OrleansAppHost/Program.cs]: Shared code works, all of the playground samlpes would include this helper extension method `AddDashboard()`. That would do the above.

File: src/Aspire.Hosting/Dashboard/DashboardManifestExclusionHook.cs [hunk 5]
```diff
@@ -0,0 +1,19 @@
...
+
+using Aspire.Hosting.ApplicationModel;
+using Aspire.Hosting.Lifecycle;
+
+namespace Aspire.Hosting.Dashboard;
+internal sealed class DashboardManifestExclusionHook : IDistributedApplicationLifecycleHook
+{
+    public Task BeforeStartAsync(DistributedApplicationModel model, CancellationToken cancellationToken)
+    {
+        if (model.Resources.SingleOrDefault(r => StringComparers.ResourceName.Equals(r.Name, KnownResourceNames.AspireDashboard)) is { } dashboardResource)
```
Comment (davidfowl) [inline src/Aspire.Hosting/Dashboard/DashboardManifestExclusionHook.cs:12]: This is cleaner

File: src/Aspire.Hosting/DistributedApplication.cs (hunk 4 above)
Comment (mitchdenny) [reply src/Aspire.Hosting/DistributedApplication.cs]: Done.

File: src/Aspire.Hosting/DistributedApplication.cs (hunk 3 above)
Comment (mitchdenny) [reply src/Aspire.Hosting/DistributedApplication.cs]: Done

**Comment by mitchdenny** [comment]
@davidfowl I think I need to move where I emit our own log messages. At the moment I'm emitting them very early and under `dotnet watch` the browser launches almost instantaneously. However you get an error page until the browser detects the server and self refreshes. So I'll change this so I emit the log messages once the dashboard itself is confirmed running.

**Comment by davidfowl** [comment]
OK, we have to log something showing that the apphost is booting up though. It should be blank until the dashboard is running.

**Comment by mitchdenny** [comment]
> OK, we have to log something showing that the apphost is booting up though. It should be blank until the dashboard is running.

Do you mean **shouldn't** be blank?

**Comment by mitchdenny** [comment]
OK so I spit out an application starting log entry as early as possible, and then I only emit the now listening message once we know the dashboard is active and we can guarantee that the browser won't see a temporary error screen.

**Comment by JamesNK** [comment]
Can we unit test this to stop it regressing again?

**Review by davidfowl — APPROVED** [review]

**Comment by mitchdenny** [comment]
@JamesNK  we'll come back for an integration test. I'll write up an issue for this

**Comment by mitchdenny** [comment]
https://github.com/dotnet/aspire/issues/1961

**Comment by davidfowl** [comment]
This needs a backport @mitchdenny
