### PR TITLE
[release/13.2] Backport: Fix 13.2 IDE execution regressions for Azure Functions and class library projects (#15714)

### LINKED ISSUE #15606: Aspire 13.2 broke AWS Lambda Integration
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Starting with Aspire 13.2 our AWS Lambda integration broke when launched in debug mode from Visual Studio. For .NET Lambda we have 2 different programming models. The complicated one for Aspire and which broke with 13.2 is where a Lambda function is defined in a class library. Our integration during startup generates a launch profile in the .NET Lambda project's `launchSettings.json` that sets up the bootstrapping executable and then we specify that launch profile for the project being launched within Aspire.

```
  "profiles": {
    "Aspire_my-lambda": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "exec --depsfile ./MyLambdaFunction.deps.json --runtimeconfig ./MyLambdaFunction.runtimeconfig.json %USERPROFILE%\\.dotnet\\tools\\.store\\amazon.lambda.testtool\\0.13.0\\amazon.lambda.testtool\\0.13.0\\content\\Amazon.Lambda.RuntimeSupport\\net10.0\\Amazon.Lambda.RuntimeSupport.TestTool.dll MyLambdaFunction::MyLambdaFunction.Function::FunctionHandler",
      "workingDirectory": "bin\\Debug\\net10.0\\"
    }
   ...
,
```

In Aspire 9.x up to 13.1 this worked fine but with 13.2 it fails with the log output indicating it doesn't like that we are using a class library even though this technic worked for us before.
```
Unable to proceed with project 'C:\Temp\AddAWSLambdaFunctionRepro\MyLambdaFunction\MyLambdaFunction.csproj'.
 Ensure you have a runnable project type.
 A runnable project should target a runnable TFM (for instance, net11.0) and have OutputType 'Exe'.
 The current OutputType is 'Library'.
```

### Expected Behavior

.NET Lambda function defined in a class library is executed following the configuration we setup in the `launchSettings.json` file.

### Steps To Reproduce

We have the following repo you can clone and reproduce the issue by opening the solution and launching the AppHost. The Lambda function will show finished right away. The repo does not require an AWS account to use.
https://github.com/dscpinheiro/AddAWSLambdaFunctionRepro

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamint**
## Description

Backport of #15714 to `release/13.2`.

Fixes regressions introduced in Aspire 13.2 where project resources using custom debug types (Azure Functions, AWS Lambda class libraries) or added via `AddResource` without `WithDebugSupport` no longer received IDE execution in Visual Studio or VS Code, breaking debugging and symbol loading.

### Changes backported

**Aspire.Hosting (C#):**
- `DcpExecutor.PrepareProjectExecutables()`: Adds a fallback branch that provides IDE execution with a standard `ProjectLaunchConfiguration` when in a debug session but either no `SupportsDebuggingAnnotation` exists (e.g. `AddResource`-based `ProjectResource` subclasses) or the IDE did not send `DEBUG_SESSION_INFO` (Visual Studio scenario where VS handles all project types natively). Restores pre-13.2 behavior.
- `ExtensionUtils.SupportsDebugging()`: Makes `"project"` launch configuration support implicit per DCP spec, so standard projects always get IDE execution even when the extension only advertises custom launch types.

**VS Code Extension (TypeScript):**
- Adds support for `Executable` command launch profiles used by AWS Lambda. When the launch profile specifies `commandName: "Executable"` with an `executablePath`, the extension builds the project and uses the profile's executable path as the debug program instead of the project output DLL.
- Adds `expandEnvironmentVariables()` to handle `$(VAR)` and `%VAR%` syntax in launch profile paths (e.g., `$(HOME)` used by AWS Lambda tool paths).
- Makes launch profile `commandName` comparison case-insensitive.
- Expands env var references in `determineWorkingDirectory`.

**Only files necessary for the fix are included** — playground apps from the original PR are excluded.

### Merge conflicts resolved
No merge conflicts — the changes applied cleanly to `release/13.2`.

### Validation
- Manual testing in VS, VS Code, and CLI have all been done.
- Norm has also confirmed that the Visual Studio experience is fixed for AWS.

Fixes #15606
Fixes #15647
Fixes #15378
Fixes #15699

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
  - [x] No

### CODE REVIEW

**Comment by joperezr** [comment]
We discussed this one offline. Marking as servicing approved as Adam confirmed all scenarios were passing and there was manual validation done to confirm it. I'll wait on @adamint to let me know when this is ready to merge as he mentioned he wanted to get additional reviews here.

**Comment by adamint** [comment]
> We discussed this one offline. Marking as servicing approved as Adam confirmed all scenarios were passing and there was manual validation done to confirm it. I'll wait on @adamint to let me know when this is ready to merge as he mentioned he wanted to get additional reviews here.

With Norm’s confirmation, I’m confident about merging

File: extension/src/debugger/launchProfiles.ts [hunk 1]
```diff
@@ -27,6 +27,26 @@ export interface LaunchProfile {
...
+ */
+export function expandEnvironmentVariables(value: string): string {
+    // Expand $(VAR) syntax (used by VS and MSBuild-style launch profiles)
+    let result = value.replace(/\$\(([^)]+)\)/g, (_, varName) => process.env[varName] ?? '');
+    // Expand %VAR% syntax (Windows)
+    result = result.replace(/%([^%]+)%/g, (_, varName) => process.env[varName] ?? '');
+    return result;
+}
+
+/**
```
Comment (JamesNK) [inline extension/src/debugger/launchProfiles.ts:42]: Nit: The two regex replacements run sequentially on the same string, so if an env var's *value* contains `%SOMETHING%` syntax, the second pass will inadvertently expand it (or collapse it to empty). For example, if `MY_VAR` = `%USERPROFILE%\tools` and input is `$(MY_VAR)/bin`, the first pass yields `%USERPROFILE%\tools/bin`, then the second pass expands `%USERPROFILE%` again. Unlikely in practice, but differs from VS's native single-pass expansion.

Not a blocker for this backport.

File: extension/src/debugger/languages/dotnet.ts [hunk 2]
```diff
@@ -253,7 +255,29 @@ export function createProjectDebuggerExtension(dotNetServiceProducer: (debugSess
...
+                // using the profile's executable path and command line arguments.
+                // Expand environment variable references (e.g. $(HOME)) that VS handles natively
+                // but aren't expanded by the coreclr debugger.
+                await dotNetService.buildDotNetProject(projectPath);
+
+                debugConfiguration.program = expandEnvironmentVariables(baseProfile.executablePath);
+                if (debugConfiguration.args) {
+                    debugConfiguration.args = expandEnvironmentVariables(debugConfiguration.args);
+                } else if (baseProfile.commandLineArgs) {
+                    // Fall back to launch profile args if run session args were empty
```
Comment (JamesNK) [inline extension/src/debugger/languages/dotnet.ts:271]: Minor: `debugConfiguration.args` was set by `determineArguments()` above. If the run session sends an explicit empty args array `[]`, `determineArguments` returns `""` (joined empty array). Since `""` is falsy, this `else if` branch would override the explicit empty args with `baseProfile.commandLineArgs`, breaking the contract that explicit run session args (even empty) take precedence over profile args.

In practice this is mitigated by the `payload.args` change in `AspireDcpServer.ts` (absent args are now `undefined`, not `[]`), so the edge case is unlikely to trigger. Consider using `debugConfiguration.args !== undefined && debugConfiguration.args !== null` instead of truthiness if porting to main.

Not a blocker for this backport.

**Review by JamesNK — APPROVED** [review]
LGTM. Two minor nits left as comments — neither is blocking for this backport. Consider addressing them when porting to main.

File: extension/src/debugger/launchProfiles.ts [hunk 3]
```diff
@@ -27,6 +27,26 @@ export interface LaunchProfile {
...
 }
 
+/**
+ * Expands environment variable references in a string.
+ * Supports $(VAR) and %VAR% syntax used by launch profiles.
+ */
+export function expandEnvironmentVariables(value: string): string {
+    // Expand $(VAR) syntax (used by VS and MSBuild-style launch profiles)
+    let result = value.replace(/\$\(([^)]+)\)/g, (_, varName) => process.env[varName] ?? '');
+    // Expand %VAR% syntax (Windows)
```
Comment (joperezr) [inline extension/src/debugger/launchProfiles.ts:37]: NIT (non-blocking, consider for main): The regex `([^)]+)` is fairly permissive — it matches any characters except `)`. A stricter pattern like `([A-Za-z_][A-Za-z0-9_]*)` would only match valid env var identifiers, reducing risk of unexpected matching on edge cases. Additionally, when a variable is not found, it's silently replaced with an empty string, which could mask typos in launch profiles (e.g., `$(TYPO_VARNAME)` → empty). A debug-level log warning for unresolved variables would help troubleshooting.

File: tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs [hunk 4]
```diff
@@ -2129,6 +2129,346 @@ public async Task ProjectExecutable_DebugSessionInfoWithNullSupportedLaunchConfi
...
+            SupportedLaunchConfigurations = ["azure-functions"]
+        };
+
+        var configDict = new Dictionary<string, string?>
+        {
+            [DcpExecutor.DebugSessionPortVar] = "12345",
+            [KnownConfigNames.DebugSessionInfo] = JsonSerializer.Serialize(runSessionInfo),
+            [KnownConfigNames.ExtensionEndpoint] = "http://localhost:1234"
+        };
+
```
Comment (joperezr) [inline tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs:2411]: NIT (non-blocking, consider for main): Several of the VS fallback tests (e.g., `StandardAndCustomProjects_VSScenario_BothRunInIde`) verify `ExecutionType.IDE` is set but don't assert that the custom-typed project (e.g., `"azure-functions"`) actually falls back to a `ProjectLaunchConfiguration` with `Type = "project"`. Without this assertion, a future regression could accidentally use the annotation's custom `ExecutableLaunchConfiguration` in the fallback path and the tests wouldn't catch it. Consider adding `Assert.Equal("project", launchConfigs[0].Type)` for the custom project in these tests.

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs [hunk 5]
```diff
@@ -1462,6 +1467,45 @@ private void PrepareProjectExecutables()
...
+    {
+        if (!isInDebugSession)
+        {
+            return false;
+        }
+
+        if (supportsDebuggingAnnotation is not null && !string.IsNullOrEmpty(_configuration[KnownConfigNames.DebugSessionInfo]))
+        {
+            return false;
+        }
```
Comment (joperezr) [inline src/Aspire.Hosting/Dcp/DcpExecutor.cs:1487]: NIT (non-blocking, consider for main): `ShouldFallBackToIdeExecution` merges two logically distinct scenarios: (1) no annotation exists (AddResource case), and (2) annotation exists but no `DebugSessionInfo` (VS case). The method name leans toward the VS fallback scenario. Additionally, if `DebugSessionInfo` JSON parsing fails (exception caught in `GetSupportedLaunchConfigurations`), it returns null and this method treats that the same as the VS case — correct behavior, but worth a brief inline comment for future readers.

File: extension/src/debugger/languages/dotnet.ts [hunk 6]
```diff
@@ -253,7 +255,29 @@ export function createProjectDebuggerExtension(dotNetServiceProducer: (debugSess
...
+                    debugConfiguration.args = expandEnvironmentVariables(baseProfile.commandLineArgs);
+                }
+                debugConfiguration.env = Object.fromEntries(mergeEnvironmentVariables(
+                    baseProfile?.environmentVariables,
+                    debugConfiguration.env,
+                    env
+                ));
```
Comment (joperezr) [inline extension/src/debugger/languages/dotnet.ts:278]: NIT (non-blocking, consider for main): The `}\nelse if` brace placement here differs from the typical TypeScript convention of `} else if` on the same line. Minor style inconsistency.

File: extension/src/test/launchProfiles.test.ts [hunk 7]
```diff
@@ -727,4 +756,56 @@ suite('Launch Profile Tests', () => {
...
+        });
+
+        test('returns string unchanged when no variables present', () => {
+            const result = expandEnvironmentVariables('/plain/path/no/vars');
+            assert.strictEqual(result, '/plain/path/no/vars');
+        });
+
+        test('expands HOME variable like AWS Lambda launch profiles use', () => {
+            const home = process.env['HOME'] ?? '';
+            const input = '$(HOME)/.dotnet/tools/.store/amazon.lambda.testtool/0.13.0/content/RuntimeSupport.dll';
```
Comment (joperezr) [inline extension/src/test/launchProfiles.test.ts:797]: NIT (non-blocking, consider for main): This test relies on `process.env['HOME']`, which may not be set on Windows CI (where `USERPROFILE` is used instead). On Windows, `HOME` could be undefined, causing the assertion to compare against empty string — the test would still pass but wouldn't be exercising real expansion. Consider using a guaranteed-present env var like `PATH`, or setting a custom test var with try/finally cleanup.

**Review by joperezr — APPROVED** [review]
LGTM — well-scoped regression fix for 4 real user-facing bugs on a servicing branch. The behavior changes are intentional, well-tested, and manually validated across VS, VS Code, and CLI.

Inline comments are all non-blocking suggestions to consider for the main branch. This PR can be merged as-is.
