### PR TITLE
Fix dashboard auth when unsecured

### LINKED ISSUE #4851: Failing test `Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme`
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2492446&view=ms.vss-test-web.build-test-results-tab&runId=53858631&resultId=100204&paneView=debug

```
  Failed Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme [10 s]
  Error Message:
   Microsoft.Playwright.PlaywrightException : Locator expected to be visible 
Call log:
  - LocatorAssertions.ToBeVisibleAsync with timeout 5000ms
  - waiting for GetByText("TestResource")
  Stack Trace:
     at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, FrameExpectOptions expectOptions, Object expected, String message) in /_/src/Playwright/Core/AssertionsBase.cs:line 84
   at Microsoft.Playwright.Core.AssertionsBase.ExpectImplAsync(String expression, ExpectedTextValue[] expectedText, Object expected, String message, FrameExpectOptions options) in /_/src/Playwright/Core/AssertionsBase.cs:line 64
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightFixture.GoToHomeAndWaitForDataGridLoad(IPage page) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightFixture.cs:line 28
   at Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.<AppBar_Change_Theme>b__1_0(IPage page) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs:line 25
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightTestsBase.RunTestAsync(Func`2 test) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs:line 27
   at Aspire.Dashboard.Tests.Integration.Playwright.PlaywrightTestsBase.RunTestAsync(Func`2 test) in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs:line 31
   at Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme() in /_/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs:line 23
--- End of stack trace from previous location ---
```

This failed earlier also - https://dev.azure.com/dnceng-public/public/_build/results?buildId=735297&view=results

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "waiting for GetByText(\"TestResource\")",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng/internal/_build/results?buildId=2492446
**Error message validated:** `[waiting for GetByText("TestResource")`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/11/2024 1:42:31 AM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[771348](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771348)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771348&view=ms.vss-test-web.build-test-results-tab&runId=19704690&resultId=100053)|dotnet/aspire#5087|
|[771310](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771310)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771310&view=ms.vss-test-web.build-test-results-tab&runId=19703914&resultId=100135)|dotnet/aspire#5168|
|[771302](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771302)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771302&view=ms.vss-test-web.build-test-results-tab&runId=19703604&resultId=100101)|dotnet/aspire#5201|
|[771281](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771281)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=771281&view=ms.vss-test-web.build-test-results-tab&runId=19703126&resultId=100258)|dotnet/aspire#5240|
|[770989](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770989)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770989&view=ms.vss-test-web.build-test-results-tab&runId=19696002&resultId=100204)|dotnet/aspire#5201|
|[770585](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770585)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770585&view=ms.vss-test-web.build-test-results-tab&runId=19683872&resultId=100063)|dotnet/aspire#5236|
|[2511721](https://dev.azure.com/dnceng/internal/_build/results?buildId=2511721)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2511721&view=ms.vss-test-web.build-test-results-tab&runId=53992387&resultId=100149)||
|[770078](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770078)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=770078&view=ms.vss-test-web.build-test-results-tab&runId=19666766&resultId=100087)|dotnet/aspire#5018|
|[2510728](https://dev.azure.com/dnceng/internal/_build/results?buildId=2510728)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2510728&view=ms.vss-test-web.build-test-results-tab&runId=53985297&resultId=100359)||
|[2507561](https://dev.azure.com/dnceng/internal/_build/results?buildId=2507561)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2507561&view=ms.vss-test-web.build-test-results-tab&runId=53963861&resultId=100198)||
|[2507219](https://dev.azure.com/dnceng/internal/_build/results?buildId=2507219)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2507219&view=ms.vss-test-web.build-test-results-tab&runId=53960307&resultId=100172)||
|[763318](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763318)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=763318&view=ms.vss-test-web.build-test-results-tab&runId=19403762&resultId=100010)|dotnet/aspire#5123|
|[2504407](https://dev.azure.com/dnceng/internal/_build/results?buildId=2504407)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2504407&view=ms.vss-test-web.build-test-results-tab&runId=53938025&resultId=100075)||
|[2504341](https://dev.azure.com/dnceng/internal/_build/results?buildId=2504341)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2504341&view=ms.vss-test-web.build-test-results-tab&runId=53937069&resultId=100103)||
|[2502563](https://dev.azure.com/dnceng/internal/_build/results?buildId=2502563)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2502563&view=ms.vss-test-web.build-test-results-tab&runId=53927193&resultId=100300)||
|[746566](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566)|dotnet/aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng-public/public/_build/results?buildId=746566&view=ms.vss-test-web.build-test-results-tab&runId=18872026&resultId=100142)|dotnet/aspire#4925|
|[2497429](https://dev.azure.com/dnceng/internal/_build/results?buildId=2497429)|dotnet-aspire|[Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests.AppBar_Change_Theme](https://dev.azure.com/dnceng//internal/_build/results?buildId=2497429&view=ms.vss-test-web.build-test-results-tab&runId=53890639&resultId=100162)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|9|17|

### LINKED ISSUE #5490: Can't access dashboard resources when enabling DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS in 8.2.0
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Modifying a newly created aspire-starter app host to set `DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true` doesn't provide access to the dashboard resources, traces, logs and metrics. This error appears instead.

image

When looking at the distributed app builder, `IsDashboardUnsecured` returns true, so we skip the API keys setup:

image

The `DashboardLifecycleHook` class sets `DASHBOARD__FRONTEND__AUTHMODE`, `DASHBOARD__RESOURCESERVICECLIENT__AUTHMODE`, and `DASHBOARD__OTLP__AUTHMODE` to `Unsecured`.

image

Yet the authorization error happens.

### Expected Behavior

Resources, logs, metrics and traces should be visible for the default apps orchestrated by the aspire-starter template.

### Steps To Reproduce

- Create a new aspire-starter project using .NET Aspire 8.2.0
- Use the code below for the app host's Program.cs
- Run the app host and open the dashboard in your browser (any profile, in private, guest mode, etc.)

```csharp
var builder = DistributedApplication.CreateBuilder([
    "DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true"
]);

var apiService = builder.AddProject<Projects.aspire_ApiService>("apiservice");

builder.AddProject<Projects.aspire_Web>("webfrontend")
    .WithExternalHttpEndpoints()
    .WithReference(apiService);

builder.Build().Run();
```

### Exceptions (if any)

_No response_

### .NET Version info

```
.NET SDK:
 Version:           8.0.401
 Commit:            811edcc344
 Workload version:  8.0.400-manifests.57f7c351
 MSBuild version:   17.11.4+37eb419ad

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.401\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400, VS 17.10.35122.118
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:              Msi
```

### Anything else?

- ASP.NET Core version: 8.0.8
- .NET Aspire version (Aspire.Hosting.AppHost): 8.2.0
- .NET Aspire workload: 8.2.0
- IDE is Rider 2024.2

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

Fixes https://github.com/dotnet/aspire/issues/5490
Fixes https://github.com/dotnet/aspire/issues/4851

Changes to auth caused the dashboard's unsecured mode to fail. I don't exactly understand what is going on, but I think that:

1. Request would come into ASP.NET Core and the `HttpContext.User` would be set with a claim **<- good**
2. The request user is set as Blazor's auth state **<- good**
3. Blazor Server circuit is created and uses SignalR user as new auth state. SignalR user is a default unauthenticated principal. I'm not sure why it's different from the HttpContext's user. **<- bad**
4. `AuthorizeRouteView` in dashboard sees unauthorized user and displays message in browser.

I fixed this by making an auth scheme handler just for unsecured mode and made it the default auth scheme if dashboard is configured to be unsecured. My guess is the SignalR was attempting to run the default auth scheme (cookies) when it gets its user and was failing because cookies isn't used in unsecured mode.

I'm not sure how to test this simply. It might require a playwright test 😬

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to aspire-docs issue: 
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/5499)

### CODE REVIEW

**Comment by radical** [comment]
> I'm not sure how to test this simply. It might require a playwright test 😬

`Aspire.Dashboard.Tests` has some playwright tests.

https://github.com/dotnet/aspire/blob/main/tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs

File: src/Aspire.Dashboard/Authentication/FrontendCompositeAuthenticationHandler.cs [hunk 1]
```diff
@@ -29,13 +28,6 @@ protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
                     parameters: new Dictionary<string, object?> { [AspirePolicyEvaluator.SuppressChallengeKey] = true }));
         }
 
-        var scheme = GetRelevantAuthenticationScheme();
-        if (scheme == null)
-        {
-            var id = new ClaimsIdentity([new Claim(OtlpAuthorization.OtlpClaimName, bool.FalseString)]);
-            return AuthenticateResult.Success(new AuthenticationTicket(new ClaimsPrincipal(id), Scheme.Name));
-        }
```
Comment (davidfowl) [inline src/Aspire.Dashboard/Authentication/FrontendCompositeAuthenticationHandler.cs:37]: So this is what didn't work with SignalR?

File: src/Aspire.Dashboard/DashboardWebApplication.cs [hunk 2]
```diff
@@ -758,13 +762,22 @@ private static void ConfigureAuthentication(WebApplicationBuilder builder, Dashb
...
-                            .RequireClaim(OtlpAuthorization.OtlpClaimName, [bool.FalseString])
+                            .RequireClaim(FrontendAuthorizationDefaults.UnsecuredClaimName)
                             .Build());
                     break;
                 default:
                     throw new NotSupportedException($"Unexpected {nameof(FrontendAuthMode)} enum member: {dashboardOptions.Frontend.AuthMode}");
             }
         });
+
+        static string ConfigureDefaultAuthScheme(DashboardOptions dashboardOptions)
```
Comment (davidfowl) [inline src/Aspire.Dashboard/DashboardWebApplication.cs:773]: This deserves a comment. What downstream parts of the app rely on these schemes.

File: src/Aspire.Dashboard/Authentication/FrontendCompositeAuthenticationHandler.cs (hunk 1 above)
Comment (JamesNK) [reply src/Aspire.Dashboard/Authentication/FrontendCompositeAuthenticationHandler.cs:37]: Yes. It worked with the initial request (otherwise the page would have been a 401) but didn't with SignalR,. The SignalR failed then flowed into Blazor, which then caused the authorized route view component to display Unauthorized.

**Review by adamint — APPROVED** [review]

**Comment by NapalmCodes** [comment]
Has this been released? I am running into this problem as well due to https needing disabled to work with a custom container component that cannot trust dotnet dev-certs.

**Comment by adkirsch** [comment]
> Has this been released? I am running into this problem as well due to https needing disabled to work with a custom container component that cannot trust dotnet dev-certs.

Would like to know as well. Just started a new project yesterday with freshly updated workload and nuget packages.

**Comment by davidfowl** [comment]
@joperezr When does the 8.2 patch ship?

**Comment by joperezr** [comment]
**For consumers of docker image**: The 8.2.0 version of the container that has the fix for this has shipped to the nightly registry of MCR. It can be found here:  https://mcr.microsoft.com/en-us/product/dotnet/nightly/aspire-dashboard/  and can be pulled via `docker pull mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.2`. It would take a couple of more weeks to also ship to the non-nightly mcr registry.

**For people using .NET Aspire dashboard via the AppHost (most common case)**: The fix will ship in .NET Aspire 8.2.1 patch, which is scheduled to ship on 9/26.
