### PR TITLE
Clear terminal input buffer before sending Aspire commands

### LINKED ISSUE #15587: VS Code Extension restart doesnt' work if terminal has pre-existing text
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

If you have a terminal command partially filled in in the aspire terminal, and then hit `restart` or `stop` on the code lens, the aspire command gets appended on to the end of the existing command making it invalid

e.g. if you have `clear` in the buffer, hitting `stop`, tries to execute 
`clear& "aspire" resource "webfrontend-szguqqpm" stop --apphost "s:\aspire-inmemorywebserver-resource\app\AppHost\Aspire.InMemoryWebServer.AppHost.csproj"`

Which is invalid and fails

### Expected Behavior

You either shouldn't be able to insert your own commands into the aspire terminal, or running `Stop` or `Restart` should clear the existing buffer.

### Steps To Reproduce

Have an app host
Image

Now hit stop

Image

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamint**
## Description

When the Aspire terminal has pre-existing text in its input buffer (e.g., a partially typed command), clicking **Stop**, **Restart**, or **Start** on a code lens or tree view appends the Aspire CLI command to the existing text, producing an invalid command that fails.

This fix sends a line-clearing control sequence before each command:
- **Unix (bash/zsh):** `Ctrl+U` (`\x15`) — clears the current input line
- **Windows (PowerShell):** `Escape` (`\x1b`) — clears the current input line

Fixes #15587

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to `aspire.dev` issue:
      - [New issue](https://github.com/microsoft/aspire.dev/issues/new)
  - [x] No

### CODE REVIEW

File: extension/src/utils/AspireTerminalProvider.ts [hunk 1]
```diff
@@ -97,6 +97,13 @@ export class AspireTerminalProvider implements vscode.Disposable {
 
         const aspireTerminal = this.getAspireTerminal();
         extensionLogOutputChannel.info(`Sending command to Aspire terminal: ${command}`);
+
+        // Clear any pre-existing text in the terminal input buffer before sending the command.
+        // Use Ctrl+U to clear the current line without sending an ESC prefix that can alter
```
Comment (JamesNK) [inline extension/src/utils/AspireTerminalProvider.ts]: `\x15` (Ctrl+U) is bound to `UnixLineDiscard` in PSReadLine's **Emacs** edit mode (default on Linux/macOS), but **is not bound** in PSReadLine's **Windows** edit mode (the default on Windows). Since the extension creates a terminal with no explicit `shellPath`, Windows users get their default shell — typically PowerShell in Windows edit mode.

This means:
- **Unix/macOS (bash/zsh)**: Fix works as intended — Ctrl+U clears the line.
- **Windows (PowerShell, default settings)**: `\x15` is likely silently ignored by PSReadLine, so the original bug (#15587) may persist for Windows users.

Consider either: (a) adding a platform-specific branch (e.g., `Escape` (`\x1b`) works in PSReadLine's Windows mode to cancel/clear the line, and you could use `process.platform === 'win32'` to select), or (b) documenting this as a Unix-focused fix with Windows as a follow-up.

**Review by JamesNK — COMMENTED** [review]
1 comment: potential platform gap with Ctrl+U on Windows PowerShell.

File: extension/src/utils/AspireTerminalProvider.ts (hunk 1 above)
Comment (adamint) [reply extension/src/utils/AspireTerminalProvider.ts]: Good catch — updated to use platform-specific branching: `\x1b` (Escape) on Windows, `\x15` (Ctrl+U) on Unix. The `\x1b` is sent via a separate `sendText(clearSequence, false)` call, so PSReadLine's escape-sequence timeout (default 50ms) ensures it's processed as a standalone Escape keypress rather than an ANSI prefix.

**Review by maddymontaquila — APPROVED** [review]
