### PR TITLE
Hide secrets in source tooltip, correct ExpressionResolver logic for non-containers

### LINKED ISSUE #7632: Password in executable args is shown on the Resources page
I have an executable resource (`dotnet ef`) with arguments that contain a connection string for another resource (database) that includes a password. The connection string including password is being displayed on the dashboard on the Resources page in the table:

Image

I've tried various different ways of adding the argument but they all result in the password being shown. Note that the argument is manually escaped with quotes.

```csharp
...

var chatAppDb = postgres.AddDatabase("chatappdb");

var efMigrate = builder.AddExecutable("ef-migrate", "dotnet", "../ChatApp1", "ef", "database", "update", "--no-build", "--connection")
    .WithArgs(context => context.Args.Add(ReferenceExpression.Create($"\"{chatAppDb.Resource}\"")))
    .WaitFor(postgres);
```

### LINKED ISSUE #7634: Secret arguments are displayed in tooltip
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When adding arguments to a resource as a secret it is correctly redacted on the dashboard resources page. However the tooltip shows the secret without any user action. I would have expected it to not show up.

Image

Going into the details popup it's also displayed without user interaction. I don't think secrets should show unless an explicit interaction like "show secrets" or click a special "eye" icon is done. Same as what is done for ENVs in the properties.

Image

Example: doing a demo with a connection string and unintentionally showing secrets.

### Expected Behavior

Execute a special gesture to reveal secrets on screen.

### Steps To Reproduce

```c#
var connectionString = builder.AddParameter("connectionString", "my-secret", secret: true);
var exe = builder.AddExecutable("myexe", "-arg1", "--connectionstring", connectionString);
```

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamint**
## Description

Took the opportunity to clean up my code in `GetSourceViewModel` as well to add a type `CommandLineInfo` instead of relying on a tuple. Hides secrets in tooltips using the same masking characters as appear in the GridValue.

Also removes logic in `ExpressionResolver` that resolves some types of expressions only for containers. All expressions except `EndpointReferenceExpression` and `EndpointReference` should be resolved for all resource types. The only other difference between containers and other types of resources is how HostUrl is resolved (special-cased for containers). 

Fixes #7634, fixes #7632

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [X] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [X] No

### CODE REVIEW

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs [hunk 1]
```diff
@@ -31,46 +34,50 @@ public class ResourceSourceViewModel(string value, List<LaunchArgument>? content
...
+                    commandLineInfo = new CommandLineInfo(Arguments: launchArguments.Select(arg => new LaunchArgument(arg, true)).ToList(), ArgumentsString: argumentsString, TooltipString: argumentsString);
                 }
             }
         }
         else if (resource.TryGetExecutableArguments(out var executableArguments) && !resource.IsProject())
         {
-            var arguments = executableArguments.IsDefaultOrEmpty ? null : executableArguments.Select(arg => new LaunchArgument(arg, true)).ToList();
-            commandLineInfo = (Arguments: arguments, string.Join(' ', executableArguments));
+            var arguments = executableArguments.IsDefaultOrEmpty ? [] : executableArguments.Select(arg => new LaunchArgument(arg, true)).ToList();
+            commandLineInfo = new CommandLineInfo(Arguments: arguments, ArgumentsString: string.Join(' ', executableArguments), TooltipString: string.Join(' ', executableArguments));
```
Comment (eerhardt) [inline src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:53]:
```suggestion
            var argumentsString = string.Join(' ', executableArguments);
            commandLineInfo = new CommandLineInfo(Arguments: arguments, ArgumentsString: argumentsString, TooltipString: argumentsString);
```

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs [hunk 2]
```diff
@@ -154,16 +154,14 @@ async Task<ResolvedValue> EvalValueProvider(IValueProvider vp)
     /// </summary>
     async ValueTask<ResolvedValue> ResolveInternalAsync(object? value)
     {
-        return (value, sourceIsContainer) switch
```
Comment (eerhardt) [inline src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:157]: Does the summary comment need to be updated at all?

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs [hunk 3]
```diff
@@ -154,16 +154,14 @@ async Task<ResolvedValue> EvalValueProvider(IValueProvider vp)
...
-            (IResourceWithConnectionString cs, true) => await ResolveInternalAsync(cs.ConnectionStringExpression).ConfigureAwait(false),
-            (ReferenceExpression ex, false) => await EvalExpressionAsync(ex).ConfigureAwait(false),
-            (ReferenceExpression ex, true) => await EvalExpressionAsync(ex).ConfigureAwait(false),
-            (EndpointReference endpointReference, true) => new(await EvalEndpointAsync(endpointReference, EndpointProperty.Url).ConfigureAwait(false), false),
-            (EndpointReferenceExpression ep, true) => new(await EvalEndpointAsync(ep.Endpoint, ep.Property).ConfigureAwait(false), false),
-            (IValueProvider vp, false) => await EvalValueProvider(vp).ConfigureAwait(false),
-            (IValueProvider vp, true) => await EvalValueProvider(vp).ConfigureAwait(false),
+            ConnectionStringReference cs => await ResolveInternalAsync(cs.Resource.ConnectionStringExpression).ConfigureAwait(false),
+            IResourceWithConnectionString cs => await ResolveInternalAsync(cs.ConnectionStringExpression).ConfigureAwait(false),
```
Comment (eerhardt) [inline src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:160]: @davidfowl @mitchdenny @davidebbo - do we even need these 2 cases? Since `ConnectionStringReference` and `IResourceWithConnectionString` implement `IValueProvider`, shouldn't this just fall to that case?

(Note we don't necessarily need to change this in this PR, but I'm just trying to understand if I have the logic correct. If we are going to backport this to 9.1, we may not want to risk a change here.)

Comment (eerhardt) [reply src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:160]: Nevermind, I think I understand why this is necessary - because we want to intercept any "host" references inside the ConnectionString and redirect them to the containerHostName.

Would it ever work if someone implemented an IValueProvider that contained a "host" reference, but wasn't one of these?

**Review by eerhardt — APPROVED** [review]
LGTM. I just had some questions for my learning.

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs (hunk 2 above)
Comment (adamint) [reply src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:157]: It does, thanks. Updated

**Comment by adamint** [comment]
Example with a connection string, like in @DamianEdwards's example in #7632 - 
image
image

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs [hunk 4]
```diff
@@ -148,22 +151,28 @@ async Task<ResolvedValue> EvalValueProvider(IValueProvider vp)
         return new ResolvedValue(value, false);
     }
 
+    async Task<ResolvedValue> ResolveConnectionStringReferenceAsync(ConnectionStringReference cs)
+    {
+        // GetValueAsync will throw if the connection string is not optional and does not exist.
+        // Invoke GetValueAsync to make sure the value isn't resolved, since we are manually resolving the expression.
+        await ((IValueProvider)cs).GetValueAsync().ConfigureAwait(false);
```
Comment (JamesNK) [inline src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:158]: This should be passed the cancellation token.

**Comment by adamint** [comment]
@eerhardt I added some additional special cases for certain resource kinds in ExpressionEvaluator, enough changes that need a re-review

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs (hunk 4 above)
Comment (JamesNK) [reply src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:158]:
```suggestion
        await ((IValueProvider)cs).GetValueAsync(cancellationToken).ConfigureAwait(false);
```

**Comment by danmoseley** [comment]
@adamint please get this in 9.1 today if possible.

**Comment by adamint** [comment]
> @adamint please get this in 9.1 today if possible.

Waiting on re-review. @eerhardt @davidfowl

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs [hunk 5]
```diff
@@ -148,22 +151,28 @@ async Task<ResolvedValue> EvalValueProvider(IValueProvider vp)
         return new ResolvedValue(value, false);
     }
 
+    async Task<ResolvedValue> ResolveConnectionStringReferenceAsync(ConnectionStringReference cs)
+    {
+        // GetValueAsync will throw if the connection string is not optional and does not exist.
+        // Invoke GetValueAsync to make sure the value isn't resolved, since we are manually resolving the expression.
```
Comment (eerhardt) [inline src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:157]: Can we beef up this comment a little bit, so it is more clear why we are calling GetValueAsync? Is it only to produce the exception and not duplicate code?

File: tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs [hunk 6]
```diff
@@ -94,7 +96,7 @@ void AddStringProperty(string propertyName, string? propertyValue)
                 value: "project",
                 contentAfterValue: [new LaunchArgument("arg2", true), new LaunchArgument("--key", true), new LaunchArgument("secret", false)],
                 valueToVisualize: "path/to/project arg2 --key secret",
-                tooltip: "path/to/project arg2 --key secret"));
+                tooltip: $"path/to/project arg2 --key {WebUtility.HtmlDecode(DashboardUIHelpers.GetMaskingText(6).Value)}"));
```
Comment (eerhardt) [inline tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs:99]: Are there other tests that should be added for this change?

**Review by eerhardt — APPROVED** [review]
The changes look good to me. Just a couple minor comments.

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs [hunk 7]
```diff
@@ -12,15 +15,15 @@ public class ResourceSourceViewModel(string value, List<LaunchArgument>? content
 
     internal static ResourceSourceViewModel? GetSourceViewModel(ResourceViewModel resource)
     {
-        (List<LaunchArgument>? Arguments, string? ArgumentsString) commandLineInfo;
+        CommandLineInfo? commandLineInfo;
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:18]: Can the code for building the CommandLineInfo be split into its own method?

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs [hunk 8]
```diff
@@ -31,46 +34,52 @@ public class ResourceSourceViewModel(string value, List<LaunchArgument>? content
...
-            {
-                return new ResourceSourceViewModel(value: Path.GetFileName(projectPath), contentAfterValue: arguments, valueToVisualize: $"{projectPath} {fullCommandLine}", tooltip: $"{projectPath} {fullCommandLine}");
-            }
-
-            // default to project path if there is no executable path or executable arguments
-            return new ResourceSourceViewModel(value: Path.GetFileName(projectPath), contentAfterValue: commandLineInfo.Arguments, valueToVisualize: projectPath, tooltip: projectPath);
+            return commandLineInfo is not null
+                ? new ResourceSourceViewModel(value: Path.GetFileName(projectPath), contentAfterValue: commandLineInfo.Arguments, valueToVisualize: $"{projectPath} {commandLineInfo.ArgumentsString}", tooltip: $"{projectPath} {commandLineInfo.TooltipString}")
+                // default to project path if there is no executable path or executable arguments
+                : new ResourceSourceViewModel(value: Path.GetFileName(projectPath), contentAfterValue: null, valueToVisualize: projectPath, tooltip: projectPath);
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:68]: There is duplication in creating the ResourceSourceViewModel in the three paths. Does it make sense to have a helper method?

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs [hunk 9]
```diff
@@ -31,46 +34,52 @@ public class ResourceSourceViewModel(string value, List<LaunchArgument>? content
                         .Select((arg, i) => new LaunchArgument(arg, IsShown: !areArgumentsSensitive[i]))
                         .ToList();
 
-                    commandLineInfo = (Arguments: arguments, argumentsString);
+                    commandLineInfo = new CommandLineInfo(
+                        Arguments: arguments,
+                        ArgumentsString: argumentsString,
+                        TooltipString: string.Join(" ", arguments.Select(arg => arg.IsShown
+                            ? arg.Value
+                            : WebUtility.HtmlDecode(DashboardUIHelpers.GetMaskingText(6).Value))));
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:42]: Add a unit test to ResourceSourceViewModel tests that tests this.

This PR could be backported so it should be well tested.

**Review by JamesNK — COMMENTED** [review]
Dashboard changes look good. Need some tests and a little clean up.

Is there a sample where this can be manually tested?

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs (hunk 9 above)
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:42]: `WebUtility.HtmlDecode` here is a bit hacky. `GetMaskingText` was indented for text that's included in the Razor page. I'm guessing the decode is neccessary to avoid the already escaped characters being escaped again.

Perhaps `GetMaskingText` should return a record that has escaped and unescaped strings on it. You would then used the unescaped string here. Could do this as a follow up change.

**Comment by JamesNK** [comment]
Is there a sample where this can be manually tested?

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs (hunk 9 above)
Comment (adamint) [reply src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:42]: Sure, changed to a record, TextMask

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs (hunk 8 above)
Comment (adamint) [reply src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:68]: Added a helper method CreateResourceSourceViewModel

File: src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs (hunk 9 above)
Comment (adamint) [reply src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs:42]: there is a case in ResourceSourceViewModel_ReturnsCorrectValue_TestData that tests this specific case!

**Comment by adamint** [comment]
> Is there a sample where this can be manually tested?

There is not, as there is no sample using ef migrate or this feature. We could add one? but I'm unsure exactly how to replicate the use case in #7632 - @DamianEdwards maybe for suggestion, or could you share the app you were referencing there?

I've been manually testing using the following, inspired by #7632 -

Update any service in TestShop.AppHost/Program.cs to include `.WithArgs(catalogDb.Resource)`

**Review by JamesNK — APPROVED** [review]

File: tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs (hunk 6 above)
Comment (adamint) [reply tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs]: Added those tests in `ExpressionResolverTests`

File: src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs [hunk 10]
```diff
@@ -148,22 +151,29 @@ async Task<ResolvedValue> EvalValueProvider(IValueProvider vp)
         return new ResolvedValue(value, false);
     }
 
+    async Task<ResolvedValue> ResolveConnectionStringReferenceAsync(ConnectionStringReference cs)
+    {
+        // We are substituting our own logic for ConnectionStringReference's GetValueAsync.
+        // However, ConnectionStringReference#GetValueAsync will throw if the connection string is not optional but is not present.
+        // To avoid duplicating that logic, we can defer to ConnectionStringReference#GetValueAsync, which will throw if needed.
+        await ((IValueProvider)cs).GetValueAsync(cancellationToken).ConfigureAwait(false);
```
Comment (davidfowl) [inline src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs:159]: I would be worried about side effects. We should only do this in the null case to avoid double evaluation in the common case.

**Comment by mitchdenny** [comment]
@adamint I was taking a closer look at this PR and I noticed a bug. Lets say I do this:

builder.Configuration["ConnectionStrings:connstring"] = "dummyvalue";
var connstring = builder.AddConnectionString("connstring");
builder.AddExecutable("pinger", "path/to/ping", "localhost", connstring);

When this renders in the console it'll look like this. The connectionstring type name itself is being rendered into the source column. I don't think that is the intention? It should just show the secret placeholder value.

image

**Comment by mitchdenny** [comment]
Also issue #7634 suggests that we should also have a show secrets button in the copy dialog. I'm not 100% sure I agree that we need to do that - but was that a deliberate choice. If it was just skipped for expediency for 9.1 and we still want to do it then we should re-open that issue or open a new one to make sure we don't loose track.

**Comment by adamint** [comment]
> Also issue #7634 suggests that we should also have a show secrets button in the copy dialog. I'm not 100% sure I agree that we need to do that - but was that a deliberate choice. If it was just skipped for expediency for 9.1 and we still want to do it then we should re-open that issue or open a new one to make sure we don't loose track.

 It's a deliberate choice, I'll make a comment in #7634 as well - opening the text visualizer _is_ an explicit action. With secret properties in the resource details view, users wouldn't otherwise be able to hide secrets without them being initially masked, of course. Here, secrets are already hidden in the source column; if users want to see all args, they can expand the column or hover to show the (masked) tooltip.
