### PR TITLE
Clear console logs from settings dialog

### LINKED ISSUE #7488: Clear all button in settings should clear console logs
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

https://github.com/dotnet/aspire/pull/7419 added support for clearing console logs. The clear all button in settings currently clears telemetry and it should be updated to also clear console logs

### Expected Behavior

Clear all button removes all removable data.

### Steps To Reproduce

_No response_

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

console-logs-settings-clear

Fixes https://github.com/dotnet/aspire/issues/7488

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [x] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [ ] No

### CODE REVIEW

**Review by davidfowl — APPROVED** [review]

File: src/Aspire.Dashboard/Model/ConsoleLogsManager.cs [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+    public async Task UpdateFiltersAsync(ConsoleLogsFilters filters)
+    {
+        _filters = filters;
+        _hasInitialized = true;
+
+        await _sessionStorage.SetAsync(BrowserStorageKeys.ConsoleLogFilters, filters).ConfigureAwait(false);
+        if (_subscriptions.Count == 0)
+        {
+            return;
+        }
```
Comment (davidfowl) [inline src/Aspire.Dashboard/Model/ConsoleLogsManager.cs:90]: Why isn't this in the lock?
