### PR TITLE
Catch errors when getting from browser storage

### LINKED ISSUE #6961: intermittent CryptographicException while running standalone aspire dashboard makes dashboard unusable
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Running latest standalone dashboard (9.0.0) via `docker run` : 
```shell
docker run --rm -it -p 8000:18888 -p 4317:18889 -p 4318:18890 --name aspire-dashboard -e DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS="true" mcr.microsoft.com/dotnet/aspire-dashboard
```

Started a spring boot Java application (spring boot 3.4.0, temurin Java 21), with the Java Otel agent 2.10.0.

The standalone dashboard (sometimes) becomes unusable, and the UI prompts to reload with an error popup: 
`An unhandled error has occurred. [Reload](http://localhost:8000/)` 

Looking at the output from the container, I see logs like: 
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The key {c02a08ff-c2ae-4876-a796-ced22b2fa4ac} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
      System.Security.Cryptography.CryptographicException: The key {c02a08ff-c2ae-4876-a796-ced22b2fa4ac} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Model.BrowserStorage.BrowserStorageBase.GetAsync[T](String key) in /_/src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:line 19
         at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 97
         at Aspire.Dashboard.Components.Pages.Metrics.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:line 106
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '_iAUph4MiFsFrX_765oiV9PkVlVfW7htVOu8qVtM8dE'.
      System.Security.Cryptography.CryptographicException: The key {c02a08ff-c2ae-4876-a796-ced22b2fa4ac} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Model.BrowserStorage.BrowserStorageBase.GetAsync[T](String key) in /_/src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:line 19
         at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 97
         at Aspire.Dashboard.Components.Pages.Metrics.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:line 106
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

Once I start seeing this, even restarting the container doesn't always clear it. Which feels very odd. 🤷 

Maybe some state saved in the browser? 

I'm writing up some internal docs, and I'm often restarting the docker container and Java app, but I tend to leave the browser tab open.

A reliable way I've found to get out of this bad state is to be very careful on the order I shutdown & startup things: 
* shut down the aspire dashboard
* kill the java app
* close the browser window
* docker run the standalone aspire dashboard
* start the java app
* navigate in the browser to localhost:8000

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Exceptions (if any)

warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: The key {c02a08ff-c2ae-4876-a796-ced22b2fa4ac} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
      System.Security.Cryptography.CryptographicException: The key {c02a08ff-c2ae-4876-a796-ced22b2fa4ac} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Model.BrowserStorage.BrowserStorageBase.GetAsync[T](String key) in /_/src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:line 19
         at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 97
         at Aspire.Dashboard.Components.Pages.Metrics.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:line 106
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit '6GFznW-gBuA4a6SiGSoFPiL3bmDSoq2ngV4blvdc9v4'.
      System.Security.Cryptography.CryptographicException: The key {c02a08ff-c2ae-4876-a796-ced22b2fa4ac} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
         at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
         at Microsoft.AspNetCore.DataProtection.DataProtectionCommonExtensions.Unprotect(IDataProtector protector, String protectedData)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.Unprotect[TValue](String purpose, String protectedJson)
         at Microsoft.AspNetCore.Components.Server.ProtectedBrowserStorage.ProtectedBrowserStorage.GetAsync[TValue](String purpose, String key)
         at Aspire.Dashboard.Model.BrowserStorage.BrowserStorageBase.GetAsync[T](String key) in /_/src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:line 19
         at Aspire.Dashboard.Components.Pages.PageExtensions.InitializeViewModelAsync[TViewModel,TSerializableViewModel](IPageWithSessionAndUrlState`2 page) in /_/src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs:line 97
         at Aspire.Dashboard.Components.Pages.Metrics.OnParametersSetAsync() in /_/src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs:line 106
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

### .NET Version info

_No response_

### Anything else?

.NET Aspire version 9.0.0
Spring Boot 3.4.0
Java 21.0.1 (eclipse temurin)
OTel Java agent 2.10.0

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

Getting values from session storage can fail if the user upgrades Aspire version, or starts and stops the standalone container, while leaving the browser open. The problem is that session state is preserved (the browser is still open) but the underlying encryption keys have changed. The data's now invalid.

Fix is to ignore errors when getting from session/local storage. In this case the session state is lost, but nothing important is saved there.

Fixes https://github.com/dotnet/aspire/issues/6961

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [x] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [x] No

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/aspire/pull/7001)

### CODE REVIEW

File: src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs [hunk 1]
```diff
@@ -5,22 +5,41 @@
 
 namespace Aspire.Dashboard.Model.BrowserStorage;
 
-public abstract class BrowserStorageBase : IBrowserStorage
+public abstract class BrowserStorageBase<T> : IBrowserStorage where T : BrowserStorageBase<T>
 {
     private readonly ProtectedBrowserStorage _protectedBrowserStorage;
 
-    protected BrowserStorageBase(ProtectedBrowserStorage protectedBrowserStorage)
+    protected BrowserStorageBase(ProtectedBrowserStorage protectedBrowserStorage, ILogger<T> logger)
```
Comment (eerhardt) [inline src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs:12]: Does this need to be `ILogger<T>`? If it was just `ILogger`, then we wouldn't need to use the TSelf inheritance pattern and `BrowserStorageBase` could remain non-generic.

**Review by adamint — APPROVED** [review]

**Review by eerhardt — APPROVED** [review]
