### PR TITLE
Split off "hide timestamp" setting from rest of console log state

### LINKED ISSUE #7137: [AzureTools][Aspire][Question] Should the "Hide Timestamp" setting also apply to "Console Logs" in Resources?
**Clean machine:** Win11 x64 24H2 ENU
**VS Version:** VS 17.13.0 Preview 3.0 [35716.79.d17.13]
**Aspire Version**: 9.1.0-preview.1.25066.1
**Apply NuGet Feeds**
**Podman Desktop:** 1.15.0
**Podman CLI:** 5.3.1

**Repro Steps:**
1.Create a new Aspire starter project -> F5 the project.
2. In the Dashboard, click on Console in the sidebar -> Click "Settings" on the Console and select "Hide Timestamps" option.
3. Navigate to Resources and click on Console Logs.
4. Check whether the timestamps in the Console Logs are shown.

**Actual:**
Timestamps are still shown in Console Logs despite choosing "Hide Timestamps" in Console.

Image

**Question:**
Should the "Hide Timestamp" setting also apply to "Console Logs" in Resources?

**More Info:**
This issue **doesn't reproduce** if I click on Console log directly or switch to different resources in the "Console Logs".

### PR DESCRIPTION
**Pull request by adamint**
## Description

This also removes it from the query string.

Fixes #7137

## Checklist

- Is this feature complete?
  - [X] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [ ] Yes
  - [X] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [X] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [X] No

### CODE REVIEW

File: src/Aspire.Dashboard/Utils/BrowserStorageKeys.cs [hunk 1]
```diff
@@ -13,6 +13,7 @@ internal static class BrowserStorageKeys
     public const string StructuredLogsPageState = "Aspire_PageState_StructuredLogs";
     public const string MetricsPageState = "Aspire_PageState_Metrics";
     public const string ConsoleLogsPageState = "Aspire_PageState_ConsoleLogs";
+    public const string ConsoleLogTimestampState = "Aspire_PageState_ConsoleLogTimestamp";
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Utils/BrowserStorageKeys.cs:16]: It's not page state. Lets make it hold settings related to the console.
```suggestion

    public const string ConsoleLogConsoleSettings = "Aspire_ConsoleLog_ConsoleSettings";
```

File: src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs [hunk 2]
```diff
@@ -536,14 +541,11 @@ public class ConsoleLogsViewModel
...
     }
 
-    public class ConsoleLogsPageState
-    {
-        public string? SelectedResource { get; set; }
-        public bool HideTimestamp { get; set; }
-    }
+    public record ConsoleLogsPageState(string? SelectedResource);
+
+    public record ConsoleLogTimestampState(bool HideTimestamp);
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs:548]: Name the type so it could have other settings in the future.
```suggestion
    public record ConsoleLogConsoleSettings(bool HideTimestamp);
```

File: src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs [hunk 3]
```diff
@@ -93,17 +89,25 @@ private sealed class ConsoleLogsSubscription
     private readonly List<MenuButtonItem> _resourceMenuItems = new();
 
     // State
+    private bool _hideTimestamp;
     public ConsoleLogsViewModel PageViewModel { get; set; } = null!;
 
     public string BasePath => DashboardUrls.ConsoleLogBasePath;
     public string SessionStorageKey => BrowserStorageKeys.ConsoleLogsPageState;
+    private const string HideTimestampStorageKey = BrowserStorageKeys.ConsoleLogTimestampState;
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs:97]: I don't think this is nessessary. Use the property on BrowserStorageKeys directly.

File: src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs [hunk 4]
```diff
@@ -308,10 +312,11 @@ private void UpdateMenuButtons()
...
     }
 
-    private async Task ToggleTimestamp(bool hideTimestamp)
+    private async Task ToggleTimestampAsync(bool hideTimestamp)
     {
-        PageViewModel.HideTimestamp = hideTimestamp;
-        await this.AfterViewModelChangedAsync(_contentLayout, waitToApplyMobileChange: false);
+        await SessionStorage.SetAsync(HideTimestampStorageKey, new ConsoleLogTimestampState(HideTimestamp: hideTimestamp));
+        _hideTimestamp = hideTimestamp;
+        StateHasChanged();
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs:319]: Is this nessessary? I would have thought that it would be triggered automatically after the click event

File: src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs [hunk 5]
```diff
@@ -308,10 +312,11 @@ private void UpdateMenuButtons()
         }
     }
 
-    private async Task ToggleTimestamp(bool hideTimestamp)
+    private async Task ToggleTimestampAsync(bool hideTimestamp)
     {
-        PageViewModel.HideTimestamp = hideTimestamp;
-        await this.AfterViewModelChangedAsync(_contentLayout, waitToApplyMobileChange: false);
+        await SessionStorage.SetAsync(HideTimestampStorageKey, new ConsoleLogTimestampState(HideTimestamp: hideTimestamp));
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs:317]: Use browser storage instead of session storage so it persists between app runs. It should be like the persisted settings for the details view.

File: src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs (hunk 4 above)
Comment (adamint) [reply src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs:319]: Surprisingly yes, it is necessary. without:
Animation

**Review by JamesNK — APPROVED** [review]
