### PR TITLE
Fix 13.2 IDE execution regressions for Azure Functions and class library projects

### LINKED ISSUE #15606: Aspire 13.2 broke AWS Lambda Integration
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

Starting with Aspire 13.2 our AWS Lambda integration broke when launched in debug mode from Visual Studio. For .NET Lambda we have 2 different programming models. The complicated one for Aspire and which broke with 13.2 is where a Lambda function is defined in a class library. Our integration during startup generates a launch profile in the .NET Lambda project's `launchSettings.json` that sets up the bootstrapping executable and then we specify that launch profile for the project being launched within Aspire.

```
  "profiles": {
    "Aspire_my-lambda": {
      "commandName": "Executable",
      "executablePath": "dotnet",
      "commandLineArgs": "exec --depsfile ./MyLambdaFunction.deps.json --runtimeconfig ./MyLambdaFunction.runtimeconfig.json %USERPROFILE%\\.dotnet\\tools\\.store\\amazon.lambda.testtool\\0.13.0\\amazon.lambda.testtool\\0.13.0\\content\\Amazon.Lambda.RuntimeSupport\\net10.0\\Amazon.Lambda.RuntimeSupport.TestTool.dll MyLambdaFunction::MyLambdaFunction.Function::FunctionHandler",
      "workingDirectory": "bin\\Debug\\net10.0\\"
    }
   ...
,
```

In Aspire 9.x up to 13.1 this worked fine but with 13.2 it fails with the log output indicating it doesn't like that we are using a class library even though this technic worked for us before.
```
Unable to proceed with project 'C:\Temp\AddAWSLambdaFunctionRepro\MyLambdaFunction\MyLambdaFunction.csproj'.
 Ensure you have a runnable project type.
 A runnable project should target a runnable TFM (for instance, net11.0) and have OutputType 'Exe'.
 The current OutputType is 'Library'.
```

### Expected Behavior

.NET Lambda function defined in a class library is executed following the configuration we setup in the `launchSettings.json` file.

### Steps To Reproduce

We have the following repo you can clone and reproduce the issue by opening the solution and launching the AppHost. The Lambda function will show finished right away. The repo does not require an AWS account to use.
https://github.com/dscpinheiro/AddAWSLambdaFunctionRepro

### Exceptions (if any)

_No response_

### .NET Version info

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by adamint**
## Description

Fixes regressions introduced in Aspire 13.2 where project resources using custom debug types (Azure Functions, AWS Lambda class libraries) or added via `AddResource` without `WithDebugSupport` no longer received IDE execution in Visual Studio or VS Code, breaking debugging and symbol loading.

In `DcpExecutor.PrepareProjectExecutables()`, adds a fallback branch that provides IDE execution with a standard `ProjectLaunchConfiguration` when in a debug session but either no `SupportsDebuggingAnnotation` exists (e.g. `AddResource`-based `ProjectResource` subclasses) or the IDE did not send `DEBUG_SESSION_INFO` (Visual Studio scenario where VS handles all project types natively). This restores pre-13.2 behavior.

In the VS Code extension, adds support for `Executable` command launch profiles used by AWS Lambda. When the launch profile specifies `commandName: "Executable"` with an `executablePath`, the extension builds the project and uses the profile's executable path as the debug program instead of the project output DLL.

Includes a `ProjectResourceExtensions` playground app for manual E2E validation of standard, custom-debug, Azure Functions, and class library project types.

Fixes #15606
Fixes #15647
Fixes #15378
Fixes #15699

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Link to `aspire.dev` issue:
      - [New issue](https://github.com/microsoft/aspire.dev/issues/new)
  - [x] No

### CODE REVIEW

**Review by danegsta — APPROVED** [review]

**Review by karolz-ms — APPROVED** [review]

File: extension/src/debugger/languages/dotnet.ts [hunk 1]
```diff
@@ -253,7 +253,21 @@ export function createProjectDebuggerExtension(dotNetServiceProducer: (debugSess
                 env.push({ name: "ASPIRE_DASHBOARD_AI_DISABLED", value: "true" });
             }
 
-            if (!isFileBasedApp(projectPath)) {
+            if (baseProfile?.commandName === 'Executable' && baseProfile.executablePath) {
```
Comment (JamesNK) [inline extension/src/debugger/languages/dotnet.ts]: Do you need to worry about case here? nit: it would be better if command names were known consts somewhere rather than inline strings.

File: playground/ProjectResourceExtensions/ProjectResourceExtensions.sln [hunk 2]
```diff
@@ -0,0 +1,48 @@
+Microsoft Visual Studio Solution File, Format Version 12.00
```
Comment (JamesNK) [inline playground/ProjectResourceExtensions/ProjectResourceExtensions.sln]: What is this solution file for? Other playground apps don't have thier own solution files.

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs [hunk 3]
```diff
@@ -1420,6 +1422,31 @@ private void PrepareProjectExecutables()
                     // Non-project launch types (e.g. azure-functions) have their launch configuration
                     // applied later in CreateExecutableAsync() after endpoints are allocated.
                 }
+                else if (isInDebugSession && (supportsDebuggingAnnotation is null || string.IsNullOrEmpty(_configuration[KnownConfigNames.DebugSessionInfo])))
```
Comment (JamesNK) [inline src/Aspire.Hosting/Dcp/DcpExecutor.cs]: nit: I think a method here that returns bool, with a name describing the situation it's testing for, would be more understandable

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs [hunk 4]
```diff
@@ -1420,6 +1422,31 @@ private void PrepareProjectExecutables()
...
+                        ?? (Debugger.IsAttached ? ExecutableLaunchMode.Debug : ExecutableLaunchMode.NoDebug);
+
+                    projectLaunchConfiguration.DisableLaunchProfile = project.TryGetLastAnnotation<ExcludeLaunchProfileAnnotation>(out _);
+                    if (!projectLaunchConfiguration.DisableLaunchProfile && project.GetEffectiveLaunchProfile() is NamedLaunchProfile namedLaunchProfile)
+                    {
+                        projectLaunchConfiguration.LaunchProfile = namedLaunchProfile.Name;
+                    }
+
+                    exe.AnnotateAsObjectList(Executable.LaunchConfigurationsAnnotation, projectLaunchConfiguration);
+                }
```
Comment (JamesNK) [inline src/Aspire.Hosting/Dcp/DcpExecutor.cs:1427]: There is a lot of duplication between this if branch and the branch above. It creating projectLaunchConfiguration be moved into a method that both places call to avoid duplication.

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs [hunk 5]
```diff
@@ -1420,6 +1422,31 @@ private void PrepareProjectExecutables()
                     // Non-project launch types (e.g. azure-functions) have their launch configuration
                     // applied later in CreateExecutableAsync() after endpoints are allocated.
```
Comment (JamesNK) [inline src/Aspire.Hosting/Dcp/DcpExecutor.cs]: Is this still true? It seems like launch configuration could now be added in the branch below

File: extension/src/debugger/languages/dotnet.ts (hunk 1 above)
Comment (adamint) [reply extension/src/debugger/languages/dotnet.ts]: Good call — added a `LaunchProfileCommandName` const object in `launchProfiles.ts` with lowercased values (`project`, `executable`) and updated both comparison sites to use `.toLowerCase()` against these consts.

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs (hunk 5 above)
Comment (adamint) [reply src/Aspire.Hosting/Dcp/DcpExecutor.cs]: It's still true for the normal `SupportsDebugging` path — non-project types like `azure-functions` get their custom launch config applied in `CreateExecutableAsync()` after endpoints are allocated. The fallback branch only kicks in when `SupportsDebugging` returns false (no annotation or no `DEBUG_SESSION_INFO`), in which case we give the resource a standard `ProjectLaunchConfiguration` here instead of waiting. Updated the comment to clarify: "unless the IDE didn't send DEBUG_SESSION_INFO (handled by the fallback branch below)".

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs (hunk 4 above)
Comment (adamint) [reply src/Aspire.Hosting/Dcp/DcpExecutor.cs:1427]: Yep, extracted `CreateProjectLaunchConfiguration(ProjectResource, IProjectMetadata)` — both the `"project"` branch and the fallback branch call it now.

File: playground/ProjectResourceExtensions/ProjectResourceExtensions.AppHost/AppHost.cs [hunk 6]
```diff
@@ -0,0 +1,83 @@
...
+// Bug #15378 repro with a real Azure Functions project. This validates that
+// AddAzureFunctionsProject resources still get IDE execution in Visual Studio
+// (DEBUG_SESSION_PORT set, no DEBUG_SESSION_INFO) so breakpoints bind.
+var funcApp = builder.AddAzureFunctionsProject<Projects.AzureFunctionsService>("azure-functions-service")
+    .WithExternalHttpEndpoints();
+
+// Bug #15606/#15647 repro: A standard project resource should always get
+// IDE execution when DEBUG_SESSION_PORT is set, even if the extension
+// advertises SupportedLaunchConfigurations that don't include "project".
+var standardService = builder.AddProject<Projects.StandardService>("standard-service")
```
[the remark this answers is not in the document]
Comment (adamint) [reply playground/ProjectResourceExtensions/ProjectResourceExtensions.AppHost/AppHost.cs]: Fixed, removed the unused local.

File: src/Aspire.Hosting/Dcp/DcpExecutor.cs (hunk 3 above)
Comment (adamint) [reply src/Aspire.Hosting/Dcp/DcpExecutor.cs]: Done — extracted to `ShouldFallBackToIdeExecution(bool isInDebugSession, SupportsDebuggingAnnotation? supportsDebuggingAnnotation)`.

File: playground/ProjectResourceExtensions/ProjectResourceExtensions.sln (hunk 2 above)
Comment (adamint) [reply playground/ProjectResourceExtensions/ProjectResourceExtensions.sln]: It was just for local dev convenience, but you're right — removed it.

**Review by JamesNK — APPROVED** [review]

**Comment by adamint** [comment]
I discovered a couple additional issues related to args handling in the vs code extension and behavior existing in VS that we should be replicating in VS Code (environment variable expansion).

I've tested these fixes with azure functions projects, lambda projects, and normal projects in both VS Code and VS as well as the CLI.

**Review by karolz-ms — APPROVED** [review]
