### PR TITLE
Disable resource command buttons while they are running

### LINKED ISSUE #7993: [WebToolsE2E][Aspire] In the Aspire Dashboard, click the stop button to stop the projects then click the start/stop button of webfrontend, two dialog notifications will display.
**REGRESSION INFO** 
1. Worked in Aspire 9.0.0

**INSTALL STEPS**
1. Clean machine: Win11 x64 ENU
2. Install SDK 9.0.200
3. Add dotnet9 feed for 9.2.0-preview.1
4. Install the latest Aspire 9.2.0-preview.1 templates
`- dotnet new install Aspire.ProjectTemplates::9.2.0-preview.1.25160.1--force`

**REPRO STEPS**
1. Open CMD, create an Aspire App using following commands:
```
dotnet new aspire-starter -o aspire1
cd aspire1
cd aspire1.apphost
```

2. Dotnet run the project in CMD, and open URL in the browser.
`dotnet run`
3. Click the stop button for both apiservice and webfrontend.
4. Click the start/stop button of webfrontend.

**NOTE**
1. This issue can also repro using Aspire 9.1

**ACTUAL**
There are two notifications displayed when clicking the stop/start of the webfrontend project.
Image

Image

**EXPECTED**
Only one notification should display when you click the button one time.

### PR DESCRIPTION
**Pull request by JamesNK**
## Description

Disable command buttons while the command is running. Avoid issues around double clicking a command.

Fixes https://github.com/dotnet/aspire/issues/7993

## Checklist

- Is this feature complete?
  - [x] Yes. Ready to ship.
  - [ ] No. Follow-up changes expected.
- Are you including unit tests for the changes and scenario tests if relevant?
  - [x] Yes
  - [ ] No
- Did you add public API?
  - [ ] Yes
    - If yes, did you have an API Review for it?
      - [ ] Yes
      - [ ] No
    - Did you add `<remarks />` and `<code />` elements on your triple slash comments?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change make any security assumptions or guarantees?
  - [ ] Yes
    - If yes, have you done a threat model and had a security review?
      - [ ] Yes
      - [ ] No
  - [x] No
- Does the change require an update in our Aspire docs?
  - [ ] Yes
    - Is this introducing a breaking change?
      - [ ] Yes
        - Link to aspire-docs issue (please use this [`breaking-change` template](https://github.com/dotnet/docs-aspire/issues/new?template=04-breaking-change.yml)):
      - [ ] No
        - Link to aspire-docs issue (please use this [`doc-idea` template](https://github.com/dotnet/docs-aspire/issues/new?template=02-docs-request.yml)):
  - [x] No

### CODE REVIEW

File: src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs [hunk 1]
```diff
@@ -17,7 +17,49 @@ public sealed class DashboardCommandExecutor(
...
+        {
+            // There may be a delay between a command finishing and the arrival of a new resource state with updated commands sent to the client.  
+            // For example:  
+            // 1. Click the stop command on a resource. The command is disabled while running.  
+            // 2. The stop command finishes, and it is re-enabled.  
+            // 3. A new resource state arrives in the dashboard, replacing the stop command with the run command.  
+            //  
+            // To prevent the stop command from being temporarily enabled, introduce a delay between a command finishing and re-enabling it in the dashboard.  
+            // This delay is chosen to balance avoiding an incorrect temporary state (since the new resource state should arrive within a second) and maintaining responsiveness.
+            await Task.Delay(TimeSpan.FromSeconds(1)).ConfigureAwait(false);
```
Comment (davidfowl) [inline src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs:53]: jank, I like it.

File: src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor [hunk 2]
```diff
@@ -38,7 +38,7 @@
                 {
                     <FluentButton Appearance="Appearance.Lightweight"
                                   Title="@(!string.IsNullOrEmpty(command.DisplayDescription) ? command.DisplayDescription : command.DisplayName)"
-                                  Disabled="@(command.State == CommandViewModelState.Disabled)"
+                                  Disabled="@(command.State == CommandViewModelState.Disabled || DashboardCommandExecutor.IsExecuting(PageViewModel.SelectedResource!.Name, command.Name))"
```
Comment (davidfowl) [inline src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor:41]: How do you know SelectedResource is not null here?

File: src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs [hunk 3]
```diff
@@ -17,7 +17,49 @@ public sealed class DashboardCommandExecutor(
...
+        finally
+        {
+            // There may be a delay between a command finishing and the arrival of a new resource state with updated commands sent to the client.  
+            // For example:  
+            // 1. Click the stop command on a resource. The command is disabled while running.  
+            // 2. The stop command finishes, and it is re-enabled.  
+            // 3. A new resource state arrives in the dashboard, replacing the stop command with the run command.  
+            //  
+            // To prevent the stop command from being temporarily enabled, introduce a delay between a command finishing and re-enabling it in the dashboard.  
+            // This delay is chosen to balance avoiding an incorrect temporary state (since the new resource state should arrive within a second) and maintaining responsiveness.
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs:52]:
```suggestion
            // There may be a delay between a command finishing and the arrival of a new resource state with updated commands sent to the client.
            // For example:
            // 1. Click the stop command on a resource. The command is disabled while running.
            // 2. The stop command finishes, and it is re-enabled.
            // 3. A new resource state arrives in the dashboard, replacing the stop command with the run command.  
            //
            // To prevent the stop command from being temporarily enabled, introduce a delay between a command finishing and re-enabling it in the dashboard.
            // This delay is chosen to balance avoiding an incorrect temporary state (since the new resource state should arrive within a second) and maintaining responsiveness.
```

File: src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs [hunk 4]
```diff
@@ -17,7 +17,49 @@ public sealed class DashboardCommandExecutor(
...
+        finally
+        {
+            // There may be a delay between a command finishing and the arrival of a new resource state with updated commands sent to the client.
+            // For example:
+            // 1. Click the stop command on a resource. The command is disabled while running.
+            // 2. The stop command finishes, and it is re-enabled.
+            // 3. A new resource state arrives in the dashboard, replacing the stop command with the run command.  
+            //
+            // To prevent the stop command from being temporarily enabled, introduce a delay between a command finishing and re-enabling it in the dashboard.
+            // This delay is chosen to balance avoiding an incorrect temporary state (since the new resource state should arrive within a second) and maintaining responsiveness.
```
Comment (JamesNK) [inline src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs:52]:
```suggestion
            // There may be a delay between a command finishing and the arrival of a new resource state with updated commands sent to the client.
            // For example:
            // 1. Click the stop command on a resource. The command is disabled while running.
            // 2. The stop command finishes, and it is re-enabled.
            // 3. A new resource state arrives in the dashboard, replacing the stop command with the run command.
            //
            // To prevent the stop command from being temporarily enabled, introduce a delay between a command finishing and re-enabling it in the dashboard.
            // This delay is chosen to balance avoiding an incorrect temporary state (since the new resource state should arrive within a second) and maintaining responsiveness.
```

**Review by davidfowl — APPROVED** [review]
